### ISSUE TITLE
revise related materials for 1.3.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#103]
Graphing Lines 1.3.0 will contain a number of UI changes, including #91, #92, #94, #97.  Related materials (teacher tips, activities, primer video,...) may need to be revised to reflect these changes.  

Screenshot updates are covered by #99.

This should be done reasonably close to the 1.3.0 release.

**Comment by pixelzoom** [comment]
@amanda-phet Heads up - RC testing for 1.3.0 release will start next week.

**Comment by amanda-phet** [comment]
Teacher tips are updated and ready to upload when the sim is published. I am not going to worry about activities/primer video.

**Comment by pixelzoom** [comment]
@amanda-phet Since the game level icons were updated in #113, are there any related materials that need to be updated?

**Comment by amanda-phet** [comment]
Updated!

**Comment by pixelzoom** [comment]
@amanda-phet 1.3.0 has been published, you may deploy revised materials.

**Comment by amanda-phet** [comment]
Done!
