### ISSUE TITLE
publish 1.3.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#107]
This sim is ready for re-publication.  The goal is to pick up:
* UI changes that make it consistent with Graphing Quadratics
* improved i18n
* general framework improvements

Assigning to @ariel-phet to schedule this.  Assign back to me when you're ready to publish.

**Comment by pixelzoom** [comment]
Pending resolution of #107.

**Comment by ariel-phet** [comment]
@pixelzoom feel free to get an RC and test issue ready for this sim anytime after February 4

**Comment by pixelzoom** [comment]
1.3.0-rc.1 is now in RC testing, see https://github.com/phetsims/QA/issues/277.

**Comment by pixelzoom** [comment]
1.3.0-rc.1 testing was completed on 2/11/19.

**Comment by pixelzoom** [comment]
1.3.0-rc.2 is now in RC testing, see https://github.com/phetsims/QA/issues/283.

**Comment by pixelzoom** [comment]
1.3.0-rc.2 testing was completed on 2/12/19.
See [phetsims/QA#283](https://github.com/phetsims/QA/issues/283).

**Comment by pixelzoom** [comment]
1.3.0-rc.3 was submitted for RC testing on 2/12/19, with 4 issues to verify.
See https://github.com/phetsims/QA/issues/286.

**Comment by pixelzoom** [comment]
1.3.0-rc.3 testing was completed on 2/14/19.
See [phetsims/QA#286](https://github.com/phetsims/QA/issues/286).

**Comment by pixelzoom** [comment]
1.3.0-rc.4 was submitted for RC testing on 2/18/19, with 4 issues to verify. 
See https://github.com/phetsims/QA/issues/290

**Comment by pixelzoom** [comment]
1.3.0-rc.4 testing was completed on 2/20/19.
See [phetsims/QA#290](https://github.com/phetsims/QA/issues/290)

**Comment by pixelzoom** [comment]
1.3.0 was published on 2/20/19: `grunt production --brands=phet --branch=1.3`

Closing.
