### ISSUE TITLE
review overlap of graphed lines and eye button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#108]
Below is the worst case, with a bit of the arrow overlapping the button. This seems acceptable to me.  But @amanda-phet would like to review. 

Note that this block sim publication.

![screenshot_933](https://user-images.githubusercontent.com/3046552/49550428-d960e400-f8a8-11e8-98eb-2239990f0f4d.png)

**Comment by pixelzoom** [comment]
Also keep in mind that it may be a saved line that overlaps the eye button.  In that case, you can't just move the line, you have to erase all saved line.  But I still don't feel like that's a significant usability problem.

**Comment by amanda-phet** [comment]
@pixelzoom do you need to revise #107? Or once this is wrapped up the sim will be ready (again) to publish?

**Comment by pixelzoom** [comment]
The sim will be ready to publish when this issue is resolved. I'll note in #107.

**Comment by KatieWoe** [comment]
This case could use some review.
![numberovereye](https://user-images.githubusercontent.com/41024075/52502370-d384c900-2b9f-11e9-9319-e0c312567145.jpg)

**Comment by pixelzoom** [comment]
We could try to mitigate overlap of the slope indicator towards the edges of the graph.  But we're likely to create other problems and (at this point) break something else.  The "eye" button is still usable, and the user can eliminate the overlap by simply moving the manipulator, or turning off the slope indicator.  So my recommendation is to leave this as is.  @amanda-phet your opinion?

**Comment by amanda-phet** [comment]
Good find @KatieWoe . I don't like this at all, but since you can only get here by switching the points around (which is somewhat tricky to do, less so on the slope screen but especially on the point-slope screen), I would like to just leave it as-is. I wish we had found it earlier, but at this point I think we need to move on.
