### ISSUE TITLE
adjust font weight?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#110]
Over in https://github.com/phetsims/graphing-lines/issues/94#issuecomment-460362188, @lmulhall-phet questioned the use of `weight: 'bold'` for math symbol fonts. 

I noted:

> ... Graphing Lines and Graphing Slope-Intercept use weight: 'bold' a lot, while Graphing Quadratics uses bold much more judiciously (and to my eye, has a cleaner look). If that's something we want to change, it would be a new issue. ...

Questions for @amanda-phet:

(1) Do we want all sims to have similar use of bold?  Or is the current discrepancy OK?  If the latter, please close this issue.

(2) If a change is desired, does this issue need to be addressed for the current RC testing, or can it be deferred to a future release?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/94#issuecomment-460367643, @amanda-phet said:

> When we made the decision to use the math font in this sim, we all agreed the appearance looked good (even if we didn't explicitly discuss the weight). I am happy keeping it bold, and I think it works well in this sim next to all of those pickers.

So closing this issue.

**Comment by amanda-phet** [comment]
>(1) Do we want all sims to have similar use of bold? Or is the current discrepancy OK? If the latter, please close this issue.

In general, I tend to go with a medium/regular weight, not bold, but I don't think it's a decision that needs to be consistent across sims.
