### ISSUE TITLE
New best given for bad time and imperfect score

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#111]
For https://github.com/phetsims/QA/issues/277
I had beaten this level with all stars at about a minute, then beaten it much slower without all the stars, but it still gave me this dialog.  I'm trying to recreate it, but haven't so far.  I was wondering if it was part of this issue: https://github.com/phetsims/graphing-lines/issues/109, or a separate issue of its own.  Was not able to replicate on published, but having trouble replicating in rc.
![notnewbest](https://user-images.githubusercontent.com/41024075/52231595-9c4caa00-2877-11e9-8528-186d878e4f92.jpg)

**Comment by pixelzoom** [comment]
Here's what I tried, and I can't reproduce the problem, everything looks correct:

1. Run Graphing Lines 1.3.0-rc.1 with ?showAnswers
2. Go to Line Game screen
3. Turn on the timer
4. Select level 1
5. Play level 1 perfectly, but leisurely. The results are:

<img width="312" alt="screenshot_1012" src="https://user-images.githubusercontent.com/3046552/52232464-d8810a00-2879-11e9-9177-86defa8c920a.png">

6. Press Continue button.  The level-selection screen also looks correct:

<img width="877" alt="screenshot_1013" src="https://user-images.githubusercontent.com/3046552/52232529-fea6aa00-2879-11e9-8186-557ee47afd57.png">

7. Play level 1 again, as fast as possible, with no correct answers. The results are:

<img width="318" alt="screenshot_1014" src="https://user-images.githubusercontent.com/3046552/52232579-239b1d00-287a-11e9-9146-ed51982b1906.png">

8. Press the Continue button. The level-selection screen still looks correct:

<img width="877" alt="screenshot_1013" src="https://user-images.githubusercontent.com/3046552/52232529-fea6aa00-2879-11e9-8186-557ee47afd57.png">

**Comment by KatieWoe** [comment]
This is essentially what I've been trying.  I've tried turning the sound on and off.  I can't think of anything different I did when I found those two instances.  I've been trying in incognito mode to avoid caching, but still no luck.  Sorry.

**Comment by pixelzoom** [comment]
@samreid asked in Slack about `BaseGameModel`:

Is this in the correct order?

```js
// game has been completed
self.setGamePhase( GamePhase.RESULTS );
if ( score > self.bestScoreProperties[ level ].get() ) {
  self.bestScoreProperties[ level ].set( score );
}
```

**Comment by pixelzoom** [comment]
Yes, that's in the correct order.  The array of best scores is irrelevant to the "results" display, displayed for GamePhase.RESULTS.   They are relevant on the level-selection screen, GamePhase.SETTINGS, which will be visible after the user presses the Continue button.

**Comment by pixelzoom** [comment]
@phet-steele provided the following clues on Slack:

1. complete a level perfectly
2. complete the same level perfectly, faster
3. try the same level again and just skip all the prompts to see the bug

I'm thinking it is just visual though, since the time under the level select button does not change

I'm telling you, isNewBestTime has to be true! otherwise we would never fall into https://github.com/phetsims/vegas/blob/master/js/LevelCompletedNode.js#L137

also it looks like nothing checks if it's a best time before calling BaseGameModel.updateBestTime()?

**Comment by KatieWoe** [comment]
Can confirm this method.  Addition: you can repeat step three to keep seeing the results.  The message pops up whether speed was faster or not.

**Comment by pixelzoom** [comment]
@phet-steele commented:
> also it looks like nothing checks if it's a best time before calling `BaseGameModel.updateBestTime`?

`updateBestTime` handles the checking. It's a no-op if the timer is off, or if the score isn't perfect.

**Comment by pixelzoom** [comment]
@phet-steele emphatically asserted the hypothesis:
> I'm telling you, isNewBestTime has to be true!

Bingo - that was indeed the problem.  `this.isNewBestTime = false` needed to be outside the `if` statement in `updateBestTime`.  See https://github.com/phetsims/graphing-lines/commit/e0b0b1c14d70bb7e51375bbbdee3c380328c0f12.

@KatieWoe or @phet-steele please verify in master.  If it looks OK, please leave this issue open for regression testing in the next RC.

**Comment by KatieWoe** [comment]
This looks ok on master

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
Confirmed in both rcs.
