### ISSUE TITLE
Color in point tool turns black when problem is solved

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#112]
For https://github.com/phetsims/QA/issues/277 and https://github.com/phetsims/QA/issues/278
May be connected to https://github.com/phetsims/graphing-lines/issues/89.  Did not appear in published version of graphing lines.

When you use the point tool on the green line in a game level the color of the point tool turns green.  However, when you have solved that problem, the color turns black.  It does not seem to happen if you answered incorrectly.
![turnsblack](https://user-images.githubusercontent.com/41024075/52234226-66f78a80-287e-11e9-90b2-0975b1fddaad.jpg)

**Comment by pixelzoom** [comment]
@KatieWoe I'm not able to reproduce this.  It might be specific to certain types of challenges, and the screenshot above is cropped.  Can you please provide move specific steps (level) and screenshots of the challenge before and after solving it?  Thanks.

**Comment by KatieWoe** [comment]
I saw on any challenge that had a green set line (I was on level one).  The ones with a black line had a similar problem where they turned green when solved, but the pointer tool didn't change.  Here are two examples, before and after being solved.  I was on Win 10 chrome.
![yes1](https://user-images.githubusercontent.com/41024075/52236667-b0e36f00-2884-11e9-8842-f2d1f4241ffb.jpg)
![yessolve1](https://user-images.githubusercontent.com/41024075/52236689-c2c51200-2884-11e9-8328-f20dbaf6f2ea.jpg)
![yes4](https://user-images.githubusercontent.com/41024075/52236673-b640b980-2884-11e9-94e1-79c1f2066904.jpg)
![yessolve4](https://user-images.githubusercontent.com/41024075/52236697-c789c600-2884-11e9-9120-5d51889563e4.jpg)
I also noticed in this last picture that the green line cuts over the black dot.  Is that intended?

**Comment by KatieWoe** [comment]
Just reproduced on Mac 10.14 safari.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @KatieWoe please verify in master. If it looks OK, please leave this issue open to regression test in the next RC.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
Confirmed in both rcs.
