### ISSUE TITLE
update icons for game levels

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/graphing-lines#113]
The art for PhET Girl looks outdated to me. Might be a good long-term goal to update the art.

![screen shot 2019-02-04 at 1 12 01 pm](https://user-images.githubusercontent.com/31285590/52234366-b3db6100-287e-11e9-8960-86224e9f0be1.png)
![screen shot 2019-02-04 at 1 14 04 pm](https://user-images.githubusercontent.com/31285590/52234390-c6ee3100-287e-11e9-9a97-efcd5a09b765.png)

**Comment by pixelzoom** [comment]
@ariel-phet @amanda-phet Any reason to do this in the current RC, since this release is supposed to be (primarily) a "visual refresh"?

**Comment by ariel-phet** [comment]
No need in the current RC. However, I will put this on @megan-phet radar

**Comment by pixelzoom** [comment]
Current artwork files are:

[game_level_icons.ai](https://github.com/phetsims/graphing-lines/blob/master/assets/game_level_icons.ai)
[Level_1.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_1.png)
[Level_2.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_2.png)
[Level_3.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_3.png)
[Level_4.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_4.png)
[Level_5.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_5.png)
[Level_5.png](https://github.com/phetsims/graphing-lines/blob/master/images/Level_6.png)

For the PNG files, please maintain the same size (300x300) and the same amount of transparent padding within the files.  That will make it possible to drop in the new PNG files without making code changes.

**Comment by megan-phet** [comment]
<img width="885" alt="screen shot 2019-02-08 at 7 45 00 pm" src="https://user-images.githubusercontent.com/40698031/52515540-2da28000-2bda-11e9-9314-3131e1b71e0f.png">

How is this?

**Comment by pixelzoom** [comment]
@amanda-phet has the final say, but I think these look great.  

@amanda-phet would you like me to incorporate these into the current RC? Assuming that file sizes and padding are identical to the original icons, it would be relative easy to substitute these new icons. It could be a long time before these sims are published from master again, and since this RC deals with "visual improvements", it would be nice to include these new icons. 

These icons don't appear in any screenshots, so we wouldn't need to redo screenshots. If the icons appear in supporting materials, it might affect https://github.com/phetsims/graphing-lines/issues/103 or https://github.com/phetsims/graphing-slope-intercept/issues/23.

**Comment by amanda-phet** [comment]
These are super cute @megan-phet ! 

Since the sim game screen background is yellow in GL and aqua in GSI, I'd like to adjust the colors a tiny bit. Can you make the shirt blue (similar to the original) or red maybe? And the line either green (like the original- to match the green y=x line in the sim) or black?

**Comment by pixelzoom** [comment]
FYI, the green used for y=x line in the sim is `rgb( 16, 178, 15 )`.

**Comment by pixelzoom** [comment]
FYI, here are specific colors:

* `y = x` and `y = -x` lines: `rgb( 16, 178, 15 )`
* Screen backgrounds in Graphing Lines: `rgb( 255, 255, 214 )`
* Screen backgrounds in Graphing Slope-Intercept: `rgb( 226, 255, 249 )`
* Level selection buttons that the icons appear on: `rgb( 180, 205, 255 )`

**Comment by pixelzoom** [comment]
We're ready to start another round of RC testing for GL and GSI. 

@amanda-phet dfo you want me to wait for the new game icons? If so...

@megan-phet when might you be able to make the changes requested in https://github.com/phetsims/graphing-lines/issues/113#issuecomment-462214754?

**Comment by ariel-phet** [comment]
@pixelzoom since these are ready, yes, do wait for the the new game icons

**Comment by megan-phet** [comment]
@ariel-phet, @amanda-phet might still make some changes, but I'll put what I have on the Google drive.

**Comment by pixelzoom** [comment]
Removing the "priority:medium" label, since it's desired to include this in the current release.

**Comment by amanda-phet** [comment]
artwork should be good to go. Thanks @lmulhall-phet for pointing this out, and @megan-phet for your quick turnaround on the artwork! 

@pixelzoom can you check that everything looks ok?

**Comment by pixelzoom** [comment]
Icons look great.  @amanda-phet and @lmulhall-phet please verify in master, or in these dev versions: [Graphing Lines 1.4.0-dev.1](https://phet-dev.colorado.edu/html/graphing-lines/1.4.0-dev.1/phet/graphing-lines_en_phet.html), [Graphing Slope-Intercept 1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.2.0-dev.1/phet/graphing-slope-intercept_en_phet.html).

**Comment by amanda-phet** [comment]
These look great to me!

**Comment by amanda-phet** [comment]
@megan-phet and I both noticed that in level 4, PhET girls foot isn't quite touching the line. I wasn't sure how to fix it, but Megan can fix it in 2 hours, so I'll try to commit that change before @pixelzoom does the next RC.

**Comment by pixelzoom** [comment]
OK, let me know when the fix is pushed to master, so that I can cherry-pick it to the 1.3 release branch.

Then please leave the issue open for regression testing in 1.3.0-rc.2.

**Comment by megan-phet** [comment]
Fixed

**Comment by amanda-phet** [comment]
new Level 4 icon and ai asset file are uploaded.

**Comment by pixelzoom** [comment]
Looks good, see master screenshot below.  Patch applied to 1.3 branch.  

Pending regression testing in 1.3.0-rc.2.

<img width="923" alt="screenshot_1040" src="https://user-images.githubusercontent.com/3046552/52660550-2242a380-2ebd-11e9-80ff-297a43d8834a.png">

**Comment by KatieWoe** [comment]
Confirmed for bot rcs.
