### ISSUE TITLE
Green line layered over black point

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#115]
For https://github.com/phetsims/QA/issues/277
There are occasions when, upon finishing a game level, the green "correct" line overlaps a point on the black "your" line.  This causes an odd effect as seen bellow.  Seen during Level one game.  Specific type of question shown bellow.
![cutover](https://user-images.githubusercontent.com/41024075/52243884-623fd000-2898-11e9-858e-3b27a5dd7d77.jpg)
![cutoverlarger](https://user-images.githubusercontent.com/41024075/52243889-65d35700-2898-11e9-8f66-905c20277cc9.jpg)

**Comment by pixelzoom** [comment]
At first I thought this was a layering issue.  But now I believe that there's a green point on top of the black point (and in front of the green line) that isn't being made visible.

**Comment by pixelzoom** [comment]
At first I thought this was a layering issue. But now I believe that there's a green point on top of the black point (and in front of the green line) that isn't being made visible for correct answers.

For example, consider this challenge:

<img width="904" alt="screenshot_1021" src="https://user-images.githubusercontent.com/3046552/52245159-a5507200-289d-11e9-8816-31434fa22f14.png">

If I have an incorrect answer, note that the black pointer turns green:

<img width="902" alt="screenshot_1022" src="https://user-images.githubusercontent.com/3046552/52245128-936ecf00-289d-11e9-8750-d03dcbcb991e.png">

But if I have a correct answer, the black point remains:

<img width="904" alt="screenshot_1023" src="https://user-images.githubusercontent.com/3046552/52245105-80f49580-289d-11e9-8545-81d82d5d332a.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit.  @KatieWoe could you please test in master?  If it looks OK, please leave this issue open so that we can regress in the next RC.

**Comment by KatieWoe** [comment]
Looks good on master.

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
Actually, I think I found another way to get this, and it is occurring on master.  For levels that have you use the spinners to complete point slope form, get it wrong, and then move your line to line up with the answer, but with the black spot in another area.  This may be acceptable, since they can move the spot to match up with the green spot.  Up to you @pixelzoom if you want to pursue this.
![stillhappens](https://user-images.githubusercontent.com/41024075/52303383-113de380-294d-11e9-90a1-1fbd7cd99031.jpg)
![zoomin](https://user-images.githubusercontent.com/41024075/52303384-113de380-294d-11e9-9b09-b66b2305157f.jpg)

**Comment by pixelzoom** [comment]
No, not acceptable.  Lines should always be behind points and manipulators.  I'll investigate.

**Comment by pixelzoom** [comment]
Note to self.  The ordering of points and lines is specified in `ChallengeGraphNode`.   Things are currently layered based on whether they are related to the "guess" or the "answer", with all things related to the answer being in front of the guess.  I need to investigate changing this so that ordering is (back to front): lines, points, manipulators, point tools.

**Comment by pixelzoom** [comment]
I made major changes to `ChallengeGraphNode` in the above commits.  The rendering order (back to front) is now:  guess line, answer line, guess point, answer point, slope indicators, manipulators, point tools.    So lines will always be behind points. 

The main risk with this change is that some point won't be made visible when it should.  I stepped through all of the levels, compared to the published version, and I didn't see any obvious problem.

@KatieWoe please verify in master.  If you want to compare to the published version, consider using the `?shuffle` query parameter.  It will give you the same _type_ of challenge (with different numeric values) in a consistent order. You can also use `?showAnswers` if you want to move more quickly.

**Comment by KatieWoe** [comment]
I didn't run into any problems on master.  I think this looks good

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
Confirmed in both rcs.
