### ISSUE TITLE
Short max widths for game answers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#117]
For https://github.com/phetsims/QA/issues/277 and https://github.com/phetsims/QA/issues/278
When the correct answer is given on a game level and it says "your line" (the one written in black) in the bottom box, the answer string is very short.  This can be noticeable without string Tests if the string is long enough.  easiest to see with stringTest=long.
![smallmaxwidths](https://user-images.githubusercontent.com/41024075/52245288-40494c00-289e-11e9-8b01-1e961a83fa38.jpg)
![yourlinebottom](https://user-images.githubusercontent.com/41024075/52245289-40494c00-289e-11e9-9cc3-d3a5c5729b4c.jpg)

**Comment by pixelzoom** [comment]
EquationBoxNode is used for both the guess and answer boxes, where the equation's `maxWidth` is set like so:

```js
60 equationNode.maxWidth = boxSize.width - ( 2 * X_MARGIN ); // constrain with for i18n
```

So I can't immediately speculate on why the answer equation would be smaller.

**Comment by pixelzoom** [comment]
Cleanup and fix in the above commits.

This was a problem with 'Graph The Line' type challenge, as identified in the upper-left corner of the screen when running with `?showAnwers`. E.g.:

![1](https://user-images.githubusercontent.com/3046552/52248616-886f6b00-28ac-11e9-92e5-a70c73f51aa2.jpg)

It now behaves properly with `stringTest=long`, e.g.:

<img width="903" alt="screenshot_1028" src="https://user-images.githubusercontent.com/3046552/52248877-b43f2080-28ad-11e9-85ad-4a376aee2c94.png">

A subclass of 'Graph The Line' challenge is 'Place The Point' challenge.  If the placement of the 3 points doesn't make a line, you'll see something like this:

![2](https://user-images.githubusercontent.com/3046552/52248736-0c295780-28ad-11e9-9098-45caabef6778.jpg)

For reasons that I won't try to explain...  With `stringTest=long`, the **'... is not a line.'** text will not fill the full width of the box, like this:

<img width="903" alt="screenshot_1027" src="https://user-images.githubusercontent.com/3046552/52248795-57dc0100-28ad-11e9-842a-d2f66e591115.png">

In practice, this will not be an issue, so I'm not going to go through the gyrations required to make it the full width of the box with `stringTest=long`.

@KatieWoe please verify in master.  If it looks OK, leave the issue open for regression testing in the next RC.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
There still seems to be a problem when the slope is undefined (seen in Graphing Lines level 1).
![slopeundefined](https://user-images.githubusercontent.com/41024075/52674309-73b05a00-2ee0-11e9-8155-eced6a7e816b.jpg)

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  Fixed in master and 1.3 in the above commits.  Please verify in master.   If all looks well, leaves this issue open for regression testing in 1.3.0-rc.3.

**Comment by KatieWoe** [comment]
This looks solved on master

**Comment by pixelzoom** [comment]
Pending verification in 1.3.0-rc.3.

**Comment by pixelzoom** [comment]
The most recent fix here broke #114 again, see https://github.com/phetsims/graphing-lines/issues/114.  So removing the "fixed-pending-testing" label.

**Comment by pixelzoom** [comment]
The most recent fix here broke #114 again, see https://github.com/phetsims/graphing-lines/issues/114#issuecomment-463278911.  So removing the "fixed-pending-testing" label. And please ignore in phetsims/QA#286 and phetsims/QA#287.

**Comment by pixelzoom** [comment]
@KatieWoe please verify this in master.  Check with #114, since they are related.

**Comment by KatieWoe** [comment]
Doesn't happen in the first screens, but still happens on game screens. @pixelzoom

**Comment by pixelzoom** [comment]
@KatieWoe can you pleased elaborate?  What problem are you still seeing related to this issue? Below are screenshots for all of the cases that you've identified so far, and text in the bottom box is the full width of the box in all cases. 

Similar to screenshot in https://github.com/phetsims/graphing-lines/issues/117#issue-406573705:

<img width="923" alt="screenshot_1071" src="https://user-images.githubusercontent.com/3046552/52980487-8a025e00-3397-11e9-8d11-0588924a5a33.png">

Similar to screenshot in https://github.com/phetsims/graphing-lines/issues/117#issuecomment-462977357, with undefined slope:

<img width="924" alt="screenshot_1070" src="https://user-images.githubusercontent.com/3046552/52980511-a7372c80-3397-11e9-9013-a3a6962cddff.png">

Similar to screenshot in https://github.com/phetsims/graphing-lines/issues/117#issuecomment-462977357, but with defined slope:

<img width="923" alt="screenshot_1069" src="https://user-images.githubusercontent.com/3046552/52980519-ae5e3a80-3397-11e9-951c-f0523623e2fd.png">

**Comment by KatieWoe** [comment]
Seen here:
![whatimeangame](https://user-images.githubusercontent.com/41024075/52980667-7277a500-3398-11e9-9c26-d5389a98c988.gif)

1. stringTest=double
2. Find a challenge where you control the slope
3. Get problem wrong and observe the length of the equation in the Your Line box.
4. Swing the line around as you would in the other screens
5. Observe changed size

**Comment by pixelzoom** [comment]
OK thanks.  This is a new problem, created by the fix for the reported problem.

**Comment by pixelzoom** [comment]
@KatieWoe The problem reported in https://github.com/phetsims/graphing-lines/issues/117#issuecomment-464918785 is fixed, please verify in master.  Also verify that this doesn't break #114.

**Comment by KatieWoe** [comment]
All looks good from what I can see

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.4.

**Comment by KatieWoe** [comment]
I did have a quick question for GL though.  I noticed that "not a line" change size depending on what happened before it.  I think this was known (https://github.com/phetsims/graphing-lines/issues/117#issuecomment-460484858) but I wanted to make sure before I oked the issue.
![differentsizes](https://user-images.githubusercontent.com/41024075/53031441-178e8e00-342a-11e9-85cc-4a271910c8fb.gif)

**Comment by pixelzoom** [comment]
So here's the dilemma... For "Place the Point" challenges, there are 3 things that can be displayed in bottom box (the "guess box"):

* an equation (e.g. `y = 2x + 3`)
* "x = N (undefined slope)"
* "... is not a line"

Only one of these is displayed depending on where the 3 points are placed, and the other 2 is invisible. All 3 share a common parent (the box's content), and `maxWidth` is set on that common parent.  But they are whether they are visible or not, all 3 contribute to the bounds of the content.

The problem only occurs when transitioning from  "x = N (undefined slope)" to "... is not a line" because the former is a longer string.  When transitioning from an equation to "... is not a line", there's no problem. This recording demonstrates that: 

![kapture 2019-02-19 at 10 44 51](https://user-images.githubusercontent.com/3046552/53036137-532e5580-3434-11e9-96fc-4230b1f0e2e3.gif)

A few things to consider:
* This is unlikely to occur in practice.
* If it does occur, there's no significant affect on usability.
* Fixing this is likely to take several more hours and require another RC. 

So my recommendation is that we do not address this for the current release.  @amanda-phet are you OK with that?

**Comment by amanda-phet** [comment]
I agree with @pixelzoom that we should not address this. I'm not sure it is worth it ever, because of the considerations you listed (unlikely to occur, and no effect on usability).

**Comment by pixelzoom** [comment]
Thanks @amanda-phet.

@KatieWoe anything else to do here, or OK to close?

**Comment by KatieWoe** [comment]
Should be ok to close.  Closing
