### ISSUE TITLE
Pink shadow stays behind when manipulator is moved

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#119]
For https://github.com/phetsims/QA/issues/278.  Likely to also be found in https://github.com/phetsims/QA/issues/277
Reminds me of https://github.com/phetsims/wave-interference/issues/238, though that was solved by a firefox update.
This was found on Level 3 of Graphing Slope-Intercept on Firefox on Mac 10.14.  I was able to see this very briefly on Win 10 firefox, but the effect disappears on its own very quickly there.  When mousing over and dragging the three pink dots that can be used to make a line in the game, a shadow appears behind the point.  When the point is being moved, the shadow moves as well.  However, on firefox (have not yet seen elsewhere) the shadow sometimes stays behind.  This is best seen on a Mac, as it seems to vanish quickly on Windows.  On Mac, it will stay as is, seemingly until the mouse clicks elsewhere on the screen.
To reproduce, go to a game level that has a problem where you create a line using these tools.  Once you have such a problem, use the mouse to drag around the points.  If it does not occur, drop the point and pick up another.  Repeat until this occurs.
![screen shot 2019-02-06 at 3 04 25 pm](https://user-images.githubusercontent.com/41024075/52377631-b5458e80-2a22-11e9-9fed-e6eb7ce956e6.png)
![screen shot 2019-02-06 at 3 05 29 pm](https://user-images.githubusercontent.com/41024075/52377632-b5458e80-2a22-11e9-8c83-807424cb3900.png)

**Comment by pixelzoom** [comment]
In Slack, @jonathanolson said:
> Trying bounds expansion first with a transparent node may help. Otherwise using `renderer:canvas` would probably also prevent it.

**Comment by pixelzoom** [comment]
The above commit uses the `renderer: 'canvas'` workaround, applied only to the manipulator's "halo".  In Manipulator.js:

```js
      var haloNode = new Circle( 1.75 * radius, {
        fill: mainColor.withAlpha( options.haloAlpha ),
        pickable: false,
        visible: false,
        renderer: 'canvas' // Workaround for Firefox graphics artifacts, see phetsims/graphing-lines/issues/119
      } );
```

Tested on all iOS 12.1.3 and macOS 10.14.2 with all supported browsers.

@KatieWoe please verify in master. If all looks OK, leave open for regression testing in next RC.

**Comment by KatieWoe** [comment]
Also looks good on master on firefox Win 10 and Mac 10.13

**Comment by pixelzoom** [comment]
Pending regression testing in the next RC.

**Comment by KatieWoe** [comment]
I saw the "appears then quickly disappears" behavior on Win 10.  Seen in Graphing Lines Level 6.
![seenpinkflash](https://user-images.githubusercontent.com/41024075/52674642-6e9fda80-2ee1-11e9-9959-bf41c801955b.gif)

**Comment by pixelzoom** [comment]
My apologies, the fix in https://github.com/phetsims/graphing-lines/commit/ba2c684ce8a58c800816289386fa5f249ec04996 did not get cherry-picked into the 1.3 branch, so it's not in 1.3.0-rc.2.   Please skip this we'll come back to it in a quick 1.3.0-rc.3.

**Comment by KatieWoe** [comment]
This looks good for both rcs on Mac and Win
