### ISSUE TITLE
update credits for 1.3.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#123]
Current credits are shown below.  @amanda-phet @KatieWoe anything to add?

<img width="761" alt="screenshot_1041" src="https://user-images.githubusercontent.com/3046552/52663640-51a8de80-2ec4-11e9-863a-cc1a9579998a.png">

**Comment by KatieWoe** [comment]
Liam, Laura, Jacob, and myself should be added to QA

**Comment by pixelzoom** [comment]
Additions to QA credits have been completed.

**Comment by pixelzoom** [comment]
Additions to QA credits have been completed:

<img width="762" alt="screenshot_1044" src="https://user-images.githubusercontent.com/3046552/52665220-4ce62980-2ec8-11e9-9f20-af4c5cb7ef9f.png">

**Comment by amanda-phet** [comment]
Can you add Megan Lai to graphic arts?

**Comment by pixelzoom** [comment]
Additions to Graphic Arts credits have been completed:

<img width="757" alt="screenshot_1047" src="https://user-images.githubusercontent.com/3046552/52676807-a0686f80-2ee8-11e9-980a-cb6509cafd50.png">

**Comment by pixelzoom** [comment]
Pending verification in 1.3.0-rc.3.

**Comment by pixelzoom** [comment]
To verify this issue, run the sim and compare to the screenshot in https://github.com/phetsims/graphing-lines/issues/123#issuecomment-462996500.

**Comment by KatieWoe** [comment]
Confirmed
