### ISSUE TITLE
IE sound may give out

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#128]
For https://github.com/phetsims/QA/issues/290 and https://github.com/phetsims/QA/issues/291
If clicking through the problems in the game quickly enough in the game, the sound may not play properly in Internet explorer.  The second "wrong" sound does not play.  A slight pause in between stops this.  At one point the sound in the sim gave out altogether, but it came back upon refreshing the sim.  Overall, I think this is an unlikely case and I believe I've only seen it on IE, so it can probably be ignored for this RC.  I'll leave that up to @pixelzoom @ariel-phet and @amanda-phet though.

**Comment by pixelzoom** [comment]
All of the sound in this sim is from common-code (vibe & vegas), so if it's a problem in this sim, I would expect it to affect other sims that have a game.  

Afaik, there hasn't been any work on vibe in awhile, so I would expect published sims to have a similar problem. But it would be good to check, to verify that this isn't a new problem in PhET code.
And it would also be good to check with @jbphet to verify that work done to add tambo (the new sound repo) is not likely to cause problems with sims that use vibe (old sound repo).

**Comment by jbphet** [comment]
We can be fairly confident that the problem described above won't be a problem once we have migrated to tambo because we made a decision to stop supporting sound at all on IE in tambo, see https://github.com/phetsims/tambo/issues/6.  Also, I plan to make sure that a sim is either user either tambo or vibe, never both.

**Comment by pixelzoom** [comment]
Since the future is tambo, and tambo is not supporting sound on IE, then there's no reason to address this issue.  Closing.  If anyone disagrees, please reopen.

@KatieWoe as usual, thanks for reporting.
