### ISSUE TITLE
List original designer in "Lead design"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#134]
In https://github.com/phetsims/natural-selection/issues/270#issuecomment-827745710, @amanda-phet said:
> @kathy-phet and I reviewed a bunch of recent HTML5 ports, and we'd like to keep up the convention of listing the original designer when we do a port. 

If that applies to this sim, please specify what you'd like changed. 

The current credits in graphing-lines-main.js are:

```js
  credits: {
    leadDesign: 'Ariel Paul',
    softwareDevelopment: 'Chris Malley (PixelZoom, Inc.)',
    team: 'Bryce Gruneich, Karina K. R. Hensberry, Patricia Loeblein, Amanda McGarry, Kathy Perkins',
    graphicArts: 'Megan Lai, Sharon Siman-Tov',
    qualityAssurance: 'Steele Dalton, Bryce Griebenow, Elise Morgan, Liam Mulhall, Oliver Orejola, Laura Rea, ' +
                      'Benjamin Roberts, Jacob Romero, Kathryn Woessner, Bryan Yoelin'
  }
```

**Comment by amanda-phet** [comment]
I believe Ariel was the lead design for both Java and HTML5 for this sim. So I recommend no change.

**Comment by pixelzoom** [comment]
Confirmed, Ariel was the lead designer of the Java version:

<img width="545" alt="screenshot_961" src="https://user-images.githubusercontent.com/3046552/116291093-71e5b080-a751-11eb-8808-ef7d3100e71b.png">

Closing.
