### ISSUE TITLE
Revise screenshots.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#136]
The look of the point tool was changed in https://github.com/phetsims/graphing-quadratics/issues/167, so screenshots will need to be revised.  This does not need to be addressed proactively, as other visual changes might be made before this sim is republished.

**Comment by marlitas** [comment]
This is being addressed as part of the upcoming region and culture publications. Over to @amanda-phet to provide the screenshots.

**Comment by pixelzoom** [comment]
This needs to be done for https://github.com/phetsims/graphing-lines/issues/142.

**Comment by Nancy-Salpepi** [comment]
@amanda-phet the current screenshots have the updated point tool already. Do you still want new ones (to show the preferences icon)?


<img width="726" alt="Screenshot 2024-02-13 at 8 17 49 AM" src="https://github.com/phetsims/graphing-lines/assets/87318828/35a7948b-3cbe-4f8f-952b-a6fdd995a132">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi It looks like you were checking Graphing Quadratics.  This is Graphing Lines.

<img width="830" alt="screenshot_3038" src="https://github.com/phetsims/graphing-lines/assets/3046552/9d054637-60a2-4c67-884d-db95ebfe8247">

**Comment by Nancy-Salpepi** [comment]
yes! Duh! Thanks @pixelzoom

**Comment by Nancy-Salpepi** [comment]
Screenshots are updated and uploaded to assets folder with the help of @KatieWoe.

**Comment by amanda-phet** [comment]
Thanks @Nancy-Salpepi ! 

Can you also do the other ones? The screenshots that end in `-screen1` etc are usually the same as the set of screenshots that includes the primary and alts, but they are created using the query parameter so that the navbar doesn't show other screens. These are usually for partners who might only show one screen at a time.

**Comment by Nancy-Salpepi** [comment]
OK. Should be good now @amanda-phet. 
Thanks again @KatieWoe!

**Comment by amanda-phet** [comment]
These look great. Thank you!
