### ISSUE TITLE
Publish Graphing Lines 1.4 and Graphing Slope-Intercept 1.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#142]
This issue is for tracking milestones and QA progress for the Graphing Lines 1.4 release.

This release will also include Graphing Slope-Intercept 1.2, since it is a subset of Graphing Lines.

From @kathy-phet in Slack#DM:
> ...looking at early Feb for when this would need to be ready.

New features will include:
* Region and Culture - see #143
* Dynamic locale and layout - see #140
* UI sounds - see #137 
* Preferences dialog (no Simulation tab)

**Comment by pixelzoom** [comment]
Also assigning this issue to @amanda-phet.  If you have any info on timeline for this publication, please add it here.

**Comment by amanda-phet** [comment]
The timeline for this sim is still early February, as far as I know.

**Comment by pixelzoom** [comment]
Got it, thanks.  It sounds like we have no timeline for this yet. So I'm going to defer work related to this issue (like #140) so that I can work on high-priority things.  @amanda-phet Please assign this back to me when I should start working on it. To have this ready for QA, I'll need a minimum of 2 weeks notice to complete the work that I need to do.

**Comment by pixelzoom** [comment]
From today's meeting with @amanda-phet @Luisav1 @marlitas @kathy-phet @pixelzoom, posted to Slack#region-and-culture:

> Graphing Lines/Slope Intercepts has been moved ahead of FAMB
> * @pixelzoom will finish out dynamic locale work
> * @Luisav1 will start adding in structure for region and culture
> * @amanda-phet  will start prepping/exporting artwork

**Comment by amanda-phet** [comment]
My work here is done with regards to artwork. Assigning to @Luisav1 and @pixelzoom to wrap up related work.

**Comment by pixelzoom** [comment]
Dev tests were added to the QA Pipeline on 3/19/24:

* https://github.com/phetsims/qa/issues/1061
* https://github.com/phetsims/qa/issues/1062

**Comment by pixelzoom** [comment]
RC versions published on 4/6/24:

* https://github.com/phetsims/qa/issues/1066
* https://github.com/phetsims/qa/issues/1067

**Comment by pixelzoom** [comment]
RC2 versions published on 4/22/24:

* https://github.com/phetsims/qa/issues/1074
* https://github.com/phetsims/qa/issues/1075

**Comment by pixelzoom** [comment]
Graphing Lines 1.4.0 and Graphing Slope-Intercept 1.2.0 were published on 4/23/24.
