### ISSUE TITLE
Add portrayals for Region and Culture feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#143]
This needs to be done for https://github.com/phetsims/graphing-lines/issues/142, with publication milestone "early Feb".

In Slack#DM, @kathy-phet said:

> Luisa would probably be the one working on adding the Character Sets options in January, using the patterns that Marla worked out and Michael reviewed.

Feel free to assign to me for review when completed.

**Comment by pixelzoom** [comment]
I'm concerned about how this issue will impact .html file size.  So before any changes were made related to this issue, I did a local build.  Here are the results:

```
% cd graphing-lines
% grunt build --allHTML
% cd build/phet
% ls -l
total 68296
-rw-r--r--  1 cmalley  staff      2644 Dec 27 15:58 dependencies.json
-rw-r--r--  1 cmalley  staff     18589 Dec 27 15:58 english-string-map.json
-rw-r--r--  1 cmalley  staff      9208 Dec 27 15:58 graphing-lines-128.png
-rw-r--r--  1 cmalley  staff     60004 Dec 27 15:58 graphing-lines-600.png
-rw-r--r--  1 cmalley  staff     32761 Dec 27 15:58 graphing-lines-ios.png
-rw-r--r--  1 cmalley  staff     71970 Dec 27 15:58 graphing-lines-twitter-card.png
-rw-r--r--  1 cmalley  staff      1101 Dec 27 15:58 graphing-lines_all_iframe_phet.html
-rw-r--r--  1 cmalley  staff   3970571 Dec 27 15:58 graphing-lines_all_phet.html
-rw-r--r--  1 cmalley  staff    977095 Dec 27 15:58 graphing-lines_all_phet.html.gz
-rw-r--r--  1 cmalley  staff  25697942 Dec 27 15:58 graphing-lines_all_phet_debug.html
-rw-r--r--  1 cmalley  staff      1100 Dec 27 15:58 graphing-lines_en_iframe_phet.html
-rw-r--r--  1 cmalley  staff   2558477 Dec 27 15:58 graphing-lines_en_phet.html
-rw-r--r--  1 cmalley  staff   1543898 Dec 27 15:58 string-map.json
drwxr-xr-x  6 cmalley  staff       192 Dec 27 15:58 xhtml/
% cd xhtml
total 7768
-rw-r--r--  1 cmalley  staff     1840 Dec 27 15:58 graphing-lines_all.xhtml
-rw-r--r--  1 cmalley  staff  1439289 Dec 27 15:58 graphing-lines_initialization_phet.js
-rw-r--r--  1 cmalley  staff    43944 Dec 27 15:58 graphing-lines_license_phet.js
-rw-r--r--  1 cmalley  staff  2484640 Dec 27 15:58 graphing-lines_phet.js
%
```

**Comment by pixelzoom** [comment]
Looking at Balancing Act… Is the code pattern used there for switching images indicative of the pattern that is being used for all sims?  If so, I have a suggestion for a very different approach that I think would be easier to implement, more robust, and easier to maintain.  Are we open to alternatives?

**Comment by amanda-phet** [comment]
Un-assigning since these images are ready to go.

**Comment by pixelzoom** [comment]
The new image files were not added to the license.json files, resulting in CT failures.  I added license entries in https://github.com/phetsims/graphing-lines/commit/02b607b2a26cdf67690b869d0fca15d9466454a8. The attribution is "created by Sharon Siman-Tov" for usa, “created by Mariah Hermsmeyer” for other regions.

**Comment by pixelzoom** [comment]
Another problem... These new files are SVG.  When SVG files are added to a repository, that repository must be added to chipper/tsconfig/all/tsconfig.json, to tell the TypeScript transpiler about them.  Otherwise builds fail in CT.  Fixed in https://github.com/phetsims/chipper/commit/0baf7578bdd9582ce6eecdc55c432d254509a66d.

**Comment by pixelzoom** [comment]
In the above commits, I ran `grunt modulify` to generate the *_svg.ts tiles (used in the code) and replaces the level*_png.ts files with usa/level*_svg.ts files.  

This allows us to do a build and see what the new size of the sim is. See results below.  I'm happy to see that the .html file sizes actually went down a bit compared to the baseline that I recorded in https://github.com/phetsims/graphing-lines/issues/143#issuecomment-1870678841. 

```
% cd graphing-lines
% grunt build --brands=phet --allHTML
% ls -lR build/phet
total 65496
-rw-r--r--  1 cmalley  staff      2644 Feb  3 13:30 dependencies.json
-rw-r--r--  1 cmalley  staff     18589 Feb  3 13:30 english-string-map.json
-rw-r--r--  1 cmalley  staff      9208 Feb  3 13:30 graphing-lines-128.png
-rw-r--r--  1 cmalley  staff     60004 Feb  3 13:30 graphing-lines-600.png
-rw-r--r--  1 cmalley  staff     32761 Feb  3 13:30 graphing-lines-ios.png
-rw-r--r--  1 cmalley  staff     71970 Feb  3 13:30 graphing-lines-twitter-card.png
-rw-r--r--  1 cmalley  staff      1101 Feb  3 13:30 graphing-lines_all_iframe_phet.html
-rw-r--r--  1 cmalley  staff   2755391 Feb  3 13:30 graphing-lines_all_phet.html
-rw-r--r--  1 cmalley  staff    885662 Feb  3 13:30 graphing-lines_all_phet.html.gz
-rw-r--r--  1 cmalley  staff  25630637 Feb  3 13:30 graphing-lines_all_phet_debug.html
-rw-r--r--  1 cmalley  staff      1100 Feb  3 13:30 graphing-lines_en_iframe_phet.html
-rw-r--r--  1 cmalley  staff   2493200 Feb  3 13:30 graphing-lines_en_phet.html
-rw-r--r--  1 cmalley  staff   1544707 Feb  3 13:30 string-map.json
drwxr-xr-x  6 cmalley  staff       192 Feb  3 13:21 xhtml/

build/phet/xhtml:
total 5392
-rw-r--r--  1 cmalley  staff     1840 Feb  3 13:30 graphing-lines_all.xhtml
-rw-r--r--  1 cmalley  staff   282391 Feb  3 13:30 graphing-lines_initialization_phet.js
-rw-r--r--  1 cmalley  staff    46890 Feb  3 13:30 graphing-lines_license_phet.js
-rw-r--r--  1 cmalley  staff  2423412 Feb  3 13:30 graphing-lines_phet.js
% 
```

**Comment by Luisav1** [comment]
In the above commits:
- @pixelzoom The portrayals structure is in GL and GSI is ready for a code review.
- @amanda-phet The artwork in GL is now integrated and ready for a design review.
- @amanda-phet GSI is awaiting the new artwork, currently GL images are being used in their place.

**Comment by pixelzoom** [comment]
Looking good @Luisav1! 

I started my review, but ran out of time.  There's more to come, but I'll started with the 2 commits above, in which I changed 2 things:

(1) There's no reason for `regionAndCulturePortrayalProperty` to be in the model. I'm guessing that you did this because it was an easier path to get it to the view.  I've moved it to the view, as a parameter to LineGameScreenView and GSILineGameScreenView.

(2) There's no reason to pass the entire PreferenceModel when all that's needs in  `regionAndCulturePortrayalProperty` -- that is an example of "excessive coupling" as mentioned in the code-review checklist.  I'll be happy to chat about that with you if it's new to you. But what it means here is that parameter `preferencesModel: PreferencesModel` has been changed to `regionAndCulturePortrayalProperty: TReadOnlyProperty<RegionAndCulturePortrayal>` throughout.

Let me know if you have questions about these.

**Comment by pixelzoom** [comment]
The next change is in the above commits. 

(1) Fields in ClimberPortrayal were missing the `readonly` keyword.

(2) The order of parameters for ClimberPortrayal was strange, with the `regionAndCultureID` inserted between some of the images, for example:

```ts
const ClimberPortrayalUSA = new ClimberPortrayal(
  unitedStatesOfAmericaStringProperty,
  level1_svg,
  level2_svg,
  level3_svg,
  level4_svg,
  USA_REGION_AND_CULTURE_ID,
  level5_svg,
  level6_svg
);
```

I changed the order so that `regionAndCultureID` is the first parameter, resulting in this nicer-looking usage:

```ts
const ClimberPortrayalUSA = new ClimberPortrayal(
  USA_REGION_AND_CULTURE_ID,
  unitedStatesOfAmericaStringProperty,
  level1_svg,
  level2_svg,
  level3_svg,
  level4_svg,
  level5_svg,
  level6_svg
);
```

**Comment by pixelzoom** [comment]
The next changes are in https://github.com/phetsims/graphing-lines/commit/796abb2ba82d3f420c58edce9e5b0bf8e71cf5a1 and https://github.com/phetsims/graphing-slope-intercept/commit/007e17923c73cccb6e92087ae1055564461147f7.

There was a lot of duplicated code in ClimberPortrayal and ClimberCharacters -- especially in ClimberCharacters.  There's no need to have a separate field for each level, like `levelOne`, `levelTwo`, `levelThree`, etc.   Because LineGameLevelSelectionButtonGroup and GSILineGameLevelSelectionButtonGroup operate on `levelImages: Node[]` as an ordered array, it's sufficient to use an array in ClimberCharacters. 

So this:

```ts
  public readonly levelOne: HTMLImageElement;
  public readonly levelTwo: HTMLImageElement;
  public readonly levelThree: HTMLImageElement;
  public readonly levelFour: HTMLImageElement;
  public readonly levelFive?: HTMLImageElement;
  public readonly levelSix?: HTMLImageElement;
```

was replaced with:

```ts
  public readonly levelImages: HTMLImageElement[];
```

and usages sites now look like:

```ts
const ClimberPortrayalUSA = new ClimberPortrayal(
  USA_REGION_AND_CULTURE_ID,
  unitedStatesOfAmericaStringProperty,
  [ level1_svg, level2_svg, level3_svg, level4_svg, level5_svg, level6_svg ]
);
```

This also eliminates the need for optional fields `levelFive?` and `levelSix?` that were needed for GSI.

And it eliminates the duplicated code in ClimberCharacters.ts.  Instead of repeating the same code for each field (`levelOne`, `levelTwo`, etc.) we just iterate over the `levelImages` array in ClimberPortrayal.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/graphing-lines/commit/6e188f260c942d2df0b5009957b260b6f45ba80e and https://github.com/phetsims/graphing-slope-intercept/commit/323c5b39b822807b8daf1fe6ee25fda894f9a97c is a change to the constructor signature of `ClimberPortrayal`.  It changes the name of param `label` to `labelProperty`, because it is a Property.  And it changes the order of param to match its superclass RegionAndCulturePortrayal, which is a best practice when subclassing.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/commit/33920b04a3382b634779910815c564bab53a80bf and https://github.com/phetsims/graphing-slope-intercept/commit/9de2d78ef34d6a627f51d6ebb9a24aa7aeaca9e0 ... ClimberImages has a single field, CLIMBER_PORTRAYALS.  I moved it to LineGameConstants.ts and GSILineGameConstants.ts, and deleted ClimberImages.ts.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/commit/4e3423756ca1ae611c28352b4256d5deab0ba54f and https://github.com/phetsims/graphing-slope-intercept/commit/ee848dea693d1c4e93b401aca43a5abc5f1e0fb4 ... ClimberCharacters would be better to implement as a factory function than as a class.  It also had a somewhat confusing name, and I believe we're trying to get away from "Characters".   I moved it to static method `createClimberNodes` in ClimberPortrayal.

**Comment by pixelzoom** [comment]
Please excuse the above commits with "move" and "Revert" comment messages.  I was trying to move portrayal-related files to a new `view/portrayals/` subdirectory.  But each time I attempted that, WebStorm was losing the git history for the files, and I reverted.  I may try to do this again later.

**Comment by pixelzoom** [comment]
Looking at some other sims, I see that some of the problems that I've pointed out for GL/GSI are patterns that you're using in all sims.   For example, in JugglerCharacters I see the same problem of lots of duplicated/boilerplate code that I saw in ClimberCharacters.    And I see lots of `*Images` files like BalancerImages, SkaterImages, etc. that really serve no purpose -- the set of portrayals could simply be added to the sim's Constants file, as I did for LineGameConstants.CLIMBER_PORTRAYALS.

So if you'd like, let's also discuss the general patterns being used to add portrayals to sims. @marlitas mights also want to participate in that discussion.

**Comment by pixelzoom** [comment]
I consulted with @jonathanolson on the 2 questions in https://github.com/phetsims/graphing-lines/issues/143#issuecomment-1933575187.   

Re (1) he strongly recommends switching to an approach where there  is 1 Image node, whose `image` is swapped based on the regionAndCulturePortrayalProperty.   I have some ideas for this, like creating `Portrayalmage extends Image` and using that in all sims.

Re (2) he agrees that ClimberPortrayal instances should be `public static readonly` members of a class, not separate files, and that we should adjust the .svg file naming to make that possible.

He also recommended making `regionAndCulturePortrayalProperty` a global Property, similar to `localeProperty`, so we don't have to dig it out of the PreferencesModel and pass it through so many layers of constructors.

@Luisav1 @marlitas let's have a meeting about this before we make futher changes. Thanks!

**Comment by marlitas** [comment]
@pixelzoom would love to have a meeting about this. I think that improvements can definitely be made here. 

I need to check on the feasibility of making `regionAndCultureProperty` a global Property. It started as a singleton and had to be changed because of PhET-iO, but I'll need to dig through some old issues to really remember the exact problems we ran into, and what went into that change. 
I'll try to set a meeting for next week so I have time to look through that info again.

**Comment by marlitas** [comment]
Link to comment explaining change from singleton to passed in property: https://github.com/phetsims/center-and-variability/issues/531#issuecomment-1712314153

**Comment by pixelzoom** [comment]
In preparation for our Feb 12 @ 10AM meeting, I tried to organize my thoughts about an alternative approach to localizing images that is similar to how PhET localizes string.  If you'd like to preview before our meeting, see [Localized Images - A Proposal](https://docs.google.com/document/d/1tEw4ETk5L9HwzB9uvrqk743i2icA-iS7PBvVgmkM1Xc/edit?usp=sharing).

**Comment by amanda-phet** [comment]
I just checked and both sims have all of the artwork and all looks correct!

**Comment by pixelzoom** [comment]
We (@marlitas @Luisav1 @jonathanolson @pixelzoom) had a meeting this morning about the general approach to implementing localized images. The implementation is going to change quite dramatically in a future iteration - it's summarized in [Localized Images - A Proposal](https://docs.google.com/document/d/1tEw4ETk5L9HwzB9uvrqk743i2icA-iS7PBvVgmkM1Xc/edit?usp=sharing).  It will require fewer changes to sim-specific code, requiring almost no new sim code, and be aligned with how PhET does string localization.  A lot of what has been added to this sim (e.g. ClimberPortrayals) and other sims will become unnecessary and will be deleted.  Image files should require no changes.

So... While the Region and Culture feature is working in this sim, someone needs to make a decision about whether we move forward with publishing Graphing Lines 1.4, or wait until we have the new implementation for image localization.  I'm not sure whose decision that should be.  So I'll assign this issue to @amanda-phet (Region and Culture lead?) and @kathy-phet.

**Comment by amanda-phet** [comment]
@Luisav1 is the region and culture champion, not me. I'll leave this assigned to @kathy-phet to determine how this fits into planning and priorities.

**Comment by Luisav1** [comment]
We (@kathy-phet, @pixelzoom, @marlitas, @jonathanolson, @amanda-phet, @Luisav1) met yesterday morning 2/14:
- Area Model sims (AMM and AMA) and Arithmetic are in/near Dev testing and RC testing so will continue with the Region & Culture implementation and publish.
- @jonathanolson and @pixelzoom will work on the common code and build tool changes necessary for the new image localization implementation.
- GL + GSI will serve as a model for new image localization approach which @pixelzoom will work on refactoring and @Luisav1 will help/follow along.
- @Luisav1 will convert all 10 other sims with R&C feature to have this new approach, create an issue in each on converting these sims.
- Remaining sims (GL + GSI, Balancing Act, FAMB, and Color Vision) will be published with this new R&C structure but the other sims will be published with the new structure whenever another publication comes up on them.
- @marlitas will consult PhET-iO team about PhET-iO implications due to converting RegionAndCultureProperty to a singleton.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/commit/57f8d287dd715f7186fb5b8ebb6843b5434d6408 and https://github.com/phetsims/graphing-slope-intercept/commit/7c301cb79c139680cb2ba98f9f4f50ade8f6ccc8, I converted to the new common code.  Most of the effort was in renaming image files, since file basenames must be unique.  I'm not quite ready to pair with @Luisav1.   There are some general issues to work out with @jonathanolson first, which I've summarized in https://github.com/phetsims/joist/issues/953#issuecomment-1977737055.

**Comment by pixelzoom** [comment]
Work is completed here.  I'll be pairing with @Luisav1 in https://github.com/phetsims/joist/issues/958.

@amanda-phet please confirm that all of the localized images look as expected, and that no regressions have been introduced. OK to close this issue if everything looks OK.

**Comment by amanda-phet** [comment]
Images look good!
