### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#144]
See `EqualityExplorerQueryParameters.getGameLevelsSchema`, and use `getGameLevelsSchema`.

**Comment by pixelzoom** [comment]
Done. Ready for review by @amanda-phet.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet @marlitas @Luisav1 FYI...

This layout with `gameLevels=1,2,3,4` was bugging me:

<img width="1030" alt="screenshot_3009" src="https://github.com/phetsims/graphing-lines/assets/3046552/ac4ba8ab-a5f1-4e54-ac15-8ba1efe1798b">

So it occurred to me that the number of buttons per row could easily be dynamic:

```ts
    const buttonsPerRow = ( GLQueryParameters.gameLevels.length <= 4 ) ? 4 : 3;
```

That results in this much nicer layout for `gameLevels=1,2,3,4`:

<img width="1024" alt="screenshot_3007" src="https://github.com/phetsims/graphing-lines/assets/3046552/63cf5106-320c-4e94-b641-ffea0c1a8547">

And with `gameLevels=1,2,3,4,5`, we then get a 2nd row of buttons:

<img width="1030" alt="screenshot_3008" src="https://github.com/phetsims/graphing-lines/assets/3046552/88759aeb-e407-4a90-a09b-859bb47bf6cd">

I also applied this improvement for fourier-making-waves.  And it was also worthwhile because there was some related TypeScript code that needed cleanup, and could have been a problem when adding the Region & Culture feature.

**Comment by pixelzoom** [comment]
Hmmm.... The GSI game screen layout doesn't look right, see below. Back to me to investigate.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Because GSI has its own game screen, with a different number of levels, it needs its own `gameLevels` query parameter.  And the value of that query parameter needs to flow through all of the components that it reuses from GL.

**Comment by amanda-phet** [comment]
`gameLevels` seems to be working well in both sims.
