### ISSUE TITLE
Optimize level-selection buttons to show off the artwork?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#145]
Related to https://github.com/phetsims/graphing-lines/issues/143 ...

The Region and Culture artwork for the level-selection buttons is really nice! So nice that I'd like to see it a little better.  Should we consider making reducing the margins inside the buttons so that the artwork is larger? Or maybe even making the buttons a bit larger?

@amanda-phet your thoughts?

For example, here are the current buttons for 'Latin America':
 
<img width="1067" alt="screenshot_3026" src="https://github.com/phetsims/graphing-lines/assets/3046552/a974e425-844f-41d5-82f4-98f8d9a9c9ad">

Here's what it looks like with larger buttons and space/margins optimized to showcase the artwork:

<img width="1065" alt="screenshot_3027" src="https://github.com/phetsims/graphing-lines/assets/3046552/5dfaf7a6-c78d-4104-9db8-fd79bb5681f1">

**Comment by amanda-phet** [comment]
I agree, the larger buttons look quite nice! Let's do that.

**Comment by pixelzoom** [comment]
Done, examples below from graphing-lines and graphing-slope-intercept.  Closing.

<img width="1062" alt="screenshot_3035" src="https://github.com/phetsims/graphing-lines/assets/3046552/021c19ec-c517-4b91-9596-a57d782f1510">

<img width="1056" alt="screenshot_3034" src="https://github.com/phetsims/graphing-lines/assets/3046552/8520082b-1877-4255-b033-df53dec18cd3">
