### ISSUE TITLE
Change default to 'random' for Region and Culture.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#147]
Related to #143 ...

Via Slack#DM, @amanda-phet requested to change the default from 'usa' to 'multi' instead for Region and Culture for GL and GSI.  This is because 'usa' shows the same person for all game levels.

**Comment by pixelzoom** [comment]
Done in the above commits.  Before having this reviewed, I'll wait for the change of 'multi' to 'random' in https://github.com/phetsims/joist/issues/957 and https://github.com/phetsims/joist/issues/954.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review, close if OK.  

Confirm by starting the sim, and verifying that the initial choice is "Random" in the Region and Culture combo box.

**Comment by amanda-phet** [comment]
Looks great.
