### ISSUE TITLE
Panels Shift

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-lines#148]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1061, on the Slope screen, the panels shift as the x and y values are changed. 

**Steps to reproduce**
Here is an example:
1. Place the purple sphere on (10,-10) and the yellow sphere on (10,4)
2. Press and hold the decrement button under the x value for the yellow sphere until it reaches -10. 
3. Then increase the value to 10.

**Visuals**

https://github.com/phetsims/graphing-lines/assets/87318828/94617102-1eaf-4bd4-94fe-7457f362d755

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Graphing Lines‬
URL: https://phet-dev.colorado.edu/html/graphing-lines/1.4.0-dev.7/phet/graphing-lines_all_phet.html
Version: 1.4.0-dev.7 2024-04-02 16:20:58 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15
Language: en-US
Window: 1324x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi. Ready for review in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in main. Closing!
