### ISSUE TITLE
Strings in Level Completed Panel need maxWidth

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-lines#150]
**Test device**
MacBook Air M1 chip 

**Operating System**
14.4.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1061, the strings in the Level Completed Panel don't have a max width.

**Steps to reproduce**
1. add ?stringTest=dynamic to the end of url
2. Complete any game level
3. Press the right arrow key a few times

**Visuals**
<img width="1426" alt="Screenshot 2024-04-03 at 10 03 22 AM" src="https://github.com/phetsims/graphing-lines/assets/87318828/96eb8c1e-e797-47be-bec0-aba2948d2a68">

**Comment by Nancy-Salpepi** [comment]
also seen in https://github.com/phetsims/qa/issues/1062

<img width="1374" alt="Screenshot 2024-04-03 at 2 11 12 PM" src="https://github.com/phetsims/graphing-lines/assets/87318828/f623cb0c-7113-41a4-ac65-27d20b761f65">

**Comment by pixelzoom** [comment]
This is LevelCompletedNode, a vegas component, which has apparently not been given the "dynamic locale" treatment.

**Comment by pixelzoom** [comment]
No changes were needed to LevelCompletedNode.  It has option `contentMaxWidth` that needs to be set.  I've done so in this sim (GL & GSI), and in the vegas demo.

@Nancy-Salpepi ready for review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in main. Closing
