### ISSUE TITLE
Update credits for 1.4 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#155]
For #142 ...

@KatieWoe please identify QA credit updates in this issue. 

The current credits are:

<img width="613" alt="screenshot_3212" src="https://github.com/phetsims/graphing-lines/assets/3046552/9a141285-8d43-4a54-9936-aa769e99a316">

**Comment by KatieWoe** [comment]
So far Nancy Salpepi and Jaron Droder should be added.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/qa/issues/1066 and https://github.com/phetsims/qa/issues/1067 RC tests have been completed. Before I deploy the next RC... @KatieWoe is there anyone else I need to add other than Nancy Salpepi and Jaron Droder?

**Comment by KatieWoe** [comment]
Nancy Salpepi, Clifford Hardin, and Jaron Droder should be added.

**Comment by amanda-phet** [comment]
Please add Mariah Hermsmeyer and Amanda McGarry to graphic arts.

**Comment by amanda-phet** [comment]
I don't see artwork from Megan Lai... is she in a license somewhere?

**Comment by pixelzoom** [comment]
Credits were updated and cherry picked in the above commits.  Screenshots  below. Ready for verification in RC2.

<img width="727" alt="screenshot_3234" src="https://github.com/phetsims/graphing-lines/assets/3046552/e81faed0-46cc-478b-99f7-27e1d91b52f0">

<img width="729" alt="screenshot_3233" src="https://github.com/phetsims/graphing-lines/assets/3046552/2ad23359-b831-48b8-a578-89fba3faf86f">

**Comment by amanda-phet** [comment]
@pixelzoom did you see my comments above?

**Comment by pixelzoom** [comment]
> @pixelzoom did you see my comments above?

Yes.  Right after I completed updates and cherry picks :(

It seems like there's some confusion about the Graphic Arts credits.  This should have been resolved before the first RC test, because images have not changed, and these changes become expensive when release branches need to be patched.  So I'm going to wait until @amanda-phet  has sorted out.  In license.json files, I see 'Sharon Siman-Tov' for the 'usa' images. 

For GSI, 'Amanda McGarry' is already credited in 'Lead Design', and we typically do not credit someone twice. 

@amanda-phet please tell me exactly what you'd like for the 'Graphic Arts' credits in GL and GSI.  This blocks RC2.

**Comment by amanda-phet** [comment]
We need to add Mariah to graphic arts, as she drew all the characters for the other regions. I'm not sure what Megan did, but she's listed in the published version so it's fine to keep her. 

You're right, I'm already listed so don't worry about adding me.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/123#issuecomment-462993657 on 2/12/2019, @amanda-phet requested to add 'Megan Lai' to the 'Graphic Arts' credits.   I don't know why -- checking out a snapshot of graphing-lines from that time, I see not image files attributed to 'Megan Lai'.   Should I remove her?

**Comment by amanda-phet** [comment]
It's possible she re-drew the phet girl level selection artwork, but Sharon was the original artist? I'm not sure it's worth digging, and since you found that request I'm sure there was a reason for it. I'm listed for graphic arts in other sims where I wasn't the artist, but spent considerable time on artwork. 

Let's just add Mariah. Thanks.

**Comment by pixelzoom** [comment]
Updated to 'Graphic Arts' credits were made in main and cherry picked in the above commits.  Screenshots shown below.  @amanda-phet please review, assign back to me if OK.

<img width="734" alt="screenshot_3235" src="https://github.com/phetsims/graphing-lines/assets/3046552/3ef269a3-f787-44e7-b1a6-5b6642f004ea">

<img width="724" alt="screenshot_3236" src="https://github.com/phetsims/graphing-lines/assets/3046552/58dcf7a7-16a1-4c76-ab0c-f19875ceeeed">

**Comment by amanda-phet** [comment]
Looks good. Thanks.

**Comment by pixelzoom** [comment]
Ready for verification in RC2.

**Comment by pixelzoom** [comment]
Ready for review in RC2 for GL and GSI.
