### ISSUE TITLE
Text shifts in top banner of game level with ?stringTest=dynamic

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#158]
For https://github.com/phetsims/qa/issues/1066 and https://github.com/phetsims/qa/issues/1067 ...

To be tested in the next RC, see https://github.com/phetsims/vegas/issues/127.   

https://github.com/phetsims/vegas/commit/18b8a3d60c7bc07beeaa1c499e0fb016f79227b8 was cherry picked for graphing-lines 1.4 and graphing-slope-intercept.

**Comment by pixelzoom** [comment]
Ready for review in RC2 for GL and GSI.  Please close this issue if it tests OK.

**Comment by Nancy-Salpepi** [comment]
I can no longer reproduce this issue in GL 1.4.0-rc.2 and GSI 1.2.0-rc.2.
Closing.

**Comment by KatieWoe** [comment]
I saw maybe a bit of shift, but it was much, much better and not very noticeable. @pixelzoom let me know if you'd like this reopened, but I don't think it's necessary.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. No need to reopen.
