### ISSUE TITLE
Start Over button can overlap text with ?stringTest=dynamic

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#159]
For https://github.com/phetsims/qa/issues/1066 and https://github.com/phetsims/qa/issues/1067.

To be verified in RC2. See https://github.com/phetsims/vegas/issues/128.

**Comment by pixelzoom** [comment]
Ready for review in GL 1.4.0-rc2 and GSI 1.2.0-rc2.  Please close this issue if it tests OK.

**Comment by Nancy-Salpepi** [comment]
I can no longer reproduce this issue in GL 1.4.0-rc.2 and GSI 1.2.0-rc.2.
Closing.
