### ISSUE TITLE
incorrect feedback for "Place the Points" challenge

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#49]
Introduced by changes in #47, and reported by @amanda-phet in https://github.com/phetsims/graphing-lines/issues/47#issuecomment-136492590. For the "Plot the Points" challenge type:

> After getting this type of challenge wrong two times, I think feedback that "your line... is not a line!" is pretty valuable. When I get it wrong two times, and make sure the 3 points are not a line, it says my line is "y = x" which is not correct.

> So, if we change the properties as you say above, we still need to give some feedback at the end if the 3 points do not make a line. If they do make a line, the sim is already clear because there is a black line and it gives the equation in the feedback.

**Comment by pixelzoom** [comment]
Fixed in this dev version:
http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-dev.3/graphing-lines_en.html

@amanda-phet please verify.

**Comment by amanda-phet** [comment]
I'm not sure what the arrangement needs to be, but occasionally I get this feedback after getting a challenge wrong one time:
![screen shot 2015-08-31 at 3 51 32 pm](https://cloud.githubusercontent.com/assets/7852916/9591391/482d4250-4ff8-11e5-9acf-9ebc23170706.png)

and then feedback that says my line is not a line, but there is a line through 2 of the points:
![screen shot 2015-08-31 at 3 51 46 pm](https://cloud.githubusercontent.com/assets/7852916/9591402/5b82e102-4ff8-11e5-8f4d-d9673ea1b847.png)

**Comment by amanda-phet** [comment]
OK, it seems to happen when the points are in an upright triangle. These two examples have black lines that don't even make sense based on the points. 

![screen shot 2015-08-31 at 3 53 40 pm](https://cloud.githubusercontent.com/assets/7852916/9591433/8f0f5d52-4ff8-11e5-8536-760e9d84a23c.png)

![screen shot 2015-08-31 at 3 53 59 pm](https://cloud.githubusercontent.com/assets/7852916/9591437/927736a4-4ff8-11e5-8529-2e289376ec83.png)

**Comment by pixelzoom** [comment]
OK, thanks, I'll investigate.  Really wishing we hadn't changed the game behavior in #47, because that violated a whole bunch of assumption for this sim that are proving difficult to track down.

**Comment by pixelzoom** [comment]
@amanda-phet OK, I think I've squashed all of the problems that this introduced. Try this dev version. And thanks for your thoroughness in discovering this issue.

 http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-dev.4/graphing-lines_en.html

**Comment by amanda-phet** [comment]
This issue seems to be resolved but I found another one :( I will open a new issue and close this one.

**Comment by amanda-phet** [comment]
Nevermind! I thought I found a new bug but it is in the original sim (and since I was only on the team for the tail end of design, I hadn't noticed this detail).

**Comment by pixelzoom** [comment]
Whew :)

And thanks!
