### ISSUE TITLE
add QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#50]
@ariel-phet This sim currently has no QA credits. Please specify the QA credits, ordered alphabetically by last name.

**Comment by ariel-phet** [comment]
Steele Dalton, Bryce Griebenow, Elise Morgan, Oliver Orejola, Benjamin Roberts, Bryan Yoelin

**Comment by amanda-phet** [comment]
@ariel-phet I also did QA but since I'm listed in the team I think I recall the rule being you wouldn't also be listed in QA. If that's the case, Bryce should not be listed in QA (he is already on the team AND interviews).

**Comment by ariel-phet** [comment]
@amanda-phet different Bryce....this is our new student tester Bryce.

**Comment by amanda-phet** [comment]
Oh sorry! I saw the last name started with G and just didn't notice the rest... oops!
