### ISSUE TITLE
Grid shown while hide grid checked

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/graphing-lines#53]
Test device: Schrodinger

Operating System: Win 8

Browser: Firefox, Chrome, and IE11

Problem description: If the check box for hide grid is checked and then the reset button is clicked, the sim will reset with grid visible and hide grid still checked.

Steps to reproduce: In any of the 3 different sections (slope, slope-intercept,or point-slope), check the hide grid box, then press the reset button. 

Severity:Minor

Screenshots:
First check hide grid
![image](https://cloud.githubusercontent.com/assets/11947677/11287867/199147fc-8edc-11e5-83b3-901ec01181d4.png)
Then reset the sim, and the grid is shown and hide grid is checked.
![image](https://cloud.githubusercontent.com/assets/11947677/11287907/69cef5de-8edc-11e5-8d23-d29c45287109.png)

Troubleshooting information (do not edit):
Name: ‪Graphing Lines‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.1/graphing-lines_en.html
Version: 1.1.0-rc.1 2015-11-16 20:17:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Language: en-US
Window: 1536x755
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16383x16383
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"288260a1","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"6735d265","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"graphing-lines":{"sha":"6e531507","branch":"1.1"},"joist":{"sha":"2a5b44c4","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"61a7c5fa","branch":"master"},"scenery":{"sha":"c0c08ec5","branch":"master"},"scenery-phet":{"sha":"61d8e7ed","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"8d290320","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"03114c7c","branch":"master"},"vibe":{"sha":"40a28182","branch":"master"}}

**Comment by pixelzoom** [comment]
Sounds like the view Property for "Hide grid" is not being reset.

**Comment by orejolaphet** [comment]
Also present in OS X 10.11.0 Safari 9.0 (11601.1.56)

**Comment by pixelzoom** [comment]
Associated with RC test https://github.com/phetsims/tasks/issues/374.

**Comment by pixelzoom** [comment]
Fix in master and 1.1 branch. This was a trivial fix, sim-specific code, does not necessitate another RC test.
