### ISSUE TITLE
need to limit width of "Slope" string

### ISSUE THREAD

**Issue by BryceAG** [phetsims/graphing-lines#55]
Test device:
Bates, Turing

Operating System:
Windows 7 64-bit, OS X 10.9.5

Browser:
FIrefox 42.0, IE 11.0.9600.17843, Chrome 46.0.2490.86 m, Safari 9.0(9537.86.1.56.2)

Problem description:
With the long test, the text box to the right gets too long and is covered by the graph. I realize that this is mostly due to the fact that the variables m, x, and y are also replaced by the long string, and that this wouldn't realistically happen; however, i think that just the word "slope" could be elongated enough to be a problem.

Steps to reproduce:
Use stringTest=long

Severity:

Screenshots:
The word "slope"
![6f9d7ee6-8c65-11e5-83b8-50d7775567d22](https://cloud.githubusercontent.com/assets/15327201/11311601/1cad3998-8f8e-11e5-80ad-da2aca890a63.png)

how long "slope" is during the test (actually circled is "m," but it's the same length, and "slope" is cut off to the left)
![72cc2068-8c65-11e5-9328-b9c70fcf3c0d2](https://cloud.githubusercontent.com/assets/15327201/11311617/3877eccc-8f8e-11e5-9a8e-ec5c69a3a5cb.png)

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.1/graphing-lines_en.html?stringTest=long
Version: 1.1.0-rc.1 2015-11-16 20:17:53 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Language: en-US
Window: 1366x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"288260a1","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"6735d265","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"graphing-lines":{"sha":"6e531507","branch":"1.1"},"joist":{"sha":"2a5b44c4","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"61a7c5fa","branch":"master"},"scenery":{"sha":"c0c08ec5","branch":"master"},"scenery-phet":{"sha":"61d8e7ed","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"8d290320","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"03114c7c","branch":"master"},"vibe":{"sha":"40a28182","branch":"master"}}

**Comment by pixelzoom** [comment]
Yep, that instance of "slope" would be a problem, need to set `maxWidth`.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/374.

**Comment by pixelzoom** [comment]
Good catch @BryceAG.

Fixed in master and 1.1 branch. Screenshot below shows the more practical case of stringTest=double. This was a 1-line fix, so does not necessitate another RC.

![screenshot_95](https://cloud.githubusercontent.com/assets/3046552/11404315/7a1da6d4-935e-11e5-8bab-cf5144b2c536.png)

**Comment by pixelzoom** [comment]
Note that the string whose maxWidth is being limited is actually "Slope   m =".
