### ISSUE TITLE
Game: correct answers are marked as incorrect for some slope values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#56]
This issue was noticed while investigating #54.  

`Line.same` is prone to floating point error (inherent in `@private Line.solveX`), and this results in correct answers being marked as incorrect in the Game.  This occurs only for specific slopes. For example, `-9/7` is one such slope, and can be demonstrated in Level 1 by changing `ChallengeFactory1` line 116 to this:

```js
challenges.push( new GraphTheLine( '1 of 3 required slopes',
  Line.createSlopeIntercept( -7, 9, yIntercept ),
  EquationForm.SLOPE_INTERCEPT, ManipulationMode.SLOPE, xRange, yRange ) );
```

And here's the incorrect behavior that occurs for this specific slope:

![screenshot_82](https://cloud.githubusercontent.com/assets/3046552/11482945/dfc3b26e-9762-11e5-8ee7-35c84fef1aac.png)

There are undoubtedly other values that yield this incorrect behavior, so this needs to be fixed for the general case.  The floating point error occurs in `@private Line.solveX`, which is called by `@private Line.onLineXY`, which is called by `@public Line.same` and `@public  Line.onLinePoint`.

**Comment by pixelzoom** [comment]
`Line.same` is used in all challenges (it appear is base type `Challenge.isCorrect`), and it's definitely a problem there, as demonstrated above.

`Line.same` is also used in `PointSlopeEquationNode` where it's used to compare a line to `y = x` and `y = -x`, then use those equation notations.  Testing shows that it's not a problem in this case.

`Line.onLinePoint` is used in `PlaceThePoint` challenges. I have not investigated whether it's a problem them.

**Comment by pixelzoom** [comment]
`Line.solveY` is apparently not really private. It's used in `PointTool.onLine`, and yield incorrect results when the point tool is placed on a line with (for example) slope `-9/7`.   For example, the point tool should "light up" in this example, since `(0,7)` is indeed on the line.

![screenshot_83](https://cloud.githubusercontent.com/assets/3046552/11483608/864f1ba2-9766-11e5-9cf1-2809c9e1b197.png)

**Comment by pixelzoom** [comment]
@ariel-phet Can you provide input in the priority of this issues, and whether it should be resolved before republishing? It's not a new problem, present in the version currently on the PhET website.  It may take awhile to resolve, and I've been getting pressure to make progress on new sims.

**Comment by pixelzoom** [comment]
Related to phetsims/tasks#374.

**Comment by ariel-phet** [comment]
Oofta...that seems important to resolve doesn't it? Showing a correct answer incorrect is pretty undesirable. So yes, I think this should be resolved before republishing, however, please work on more in the background, and continue to make progress on new sims. I would describe priority as "medium-low" - sort of a sauce simmering priority.

**Comment by pixelzoom** [comment]
In the above commits, I replaced some code in PointTool that was essentially a duplicate of Line.onLinePoint. Tested point tool in all screens with various slopes, including 0 and undefined.

**Comment by pixelzoom** [comment]
In PlaceThePoint challenges, the point tools are not calling `Line.onLinePoint`. Need to investigate why.

**Comment by pixelzoom** [comment]
Issue resolved in above commits. This can be spot tested on a couple of platforms in a new RC version.
