### ISSUE TITLE
String Tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/graphing-lines#57]
Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Safari 9.0.1 (10601.2.7.2)

Problem description: Long and RTL string Tests 

Steps to reproduce:

Severity:

Screenshots:
Long:
![screen shot 2015-12-03 at 3 53 56 pm](https://cloud.githubusercontent.com/assets/12610678/11576767/60969864-99d6-11e5-9009-469aea45125e.jpg)
![screen shot 2015-12-03 at 3 53 46 pm](https://cloud.githubusercontent.com/assets/12610678/11576768/6096edc8-99d6-11e5-851b-a4ca5a903664.jpg)
![screen shot 2015-12-03 at 3 53 30 pm](https://cloud.githubusercontent.com/assets/12610678/11576769/6098a122-99d6-11e5-8aff-8e567ef2fff7.jpg)

RTL: Looks like there could potentially be text overlap in other languages that use more characters. Only seen on Point-Slope screen. 
![screen shot 2015-12-03 at 3 53 17 pm](https://cloud.githubusercontent.com/assets/12610678/11576782/794dbce8-99d6-11e5-8000-d7156f648d69.jpg)

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-dev.5/graphing-lines_en.html?stringTest=long
Version: 1.1.0-dev.5 2015-11-29 02:41:27 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7
Language: en-us
Window: 1238x662
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"6e86b921","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"graphing-lines":{"sha":"e10ad3de","branch":"1.1"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"61a7c5fa","branch":"HEAD"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"8d290320","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"03114c7c","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by elisemorgan** [comment]
Ah, you already know this. oops

**Comment by pixelzoom** [comment]
Yep, but thanks for reporting anyway.  The overlap in the RTL test is not really relevant here because the mathematical symbols (x, y, m,...) would not be this long.
