### ISSUE TITLE
remaining 1.1.0 redeploy items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#58]
**Design/Admin**

- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date

**Comment by ariel-phet** [comment]
@amanda-phet - I took a quick peek at the teacher tips, for some reason the screenshots seem really low res. Perhaps we should update (or as a student worker to update)?

**Comment by amanda-phet** [comment]
I recently updated a bunch of teacher tips and this happened to them all. It's on my list to fix and will do it soon.

**Comment by amanda-phet** [comment]
The teacher tips have been updated. Can I close this?

**Comment by ariel-phet** [comment]
Yes, thank you! Closing!
