### ISSUE TITLE
Edge stroke between "mx"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-lines#60]
@pixelzoom there is a very apparent line between the "m" and "x" in the equation on the Slope-Intercept screen (immediately upon loading the sim). My hunch is that it is related to phetsims/trig-tour/issues/72.

![graphingstroke](https://cloud.githubusercontent.com/assets/5863899/13263361/7006ec64-da26-11e5-874e-c84e0e60c019.PNG)

I see this only in Edge (20+), both on the production version and @jonathanolson's maintenance version (2/22). Discovered during phetsims/tasks/issues/523.

Troubleshooting information:
Name: ‪Graphing Lines‬
URL: http://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html
Version: 1.1.1 2016-02-11 22:41:13 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
Language: en-US
Window: 1920x934
Pixel Ratio: 1/1
WebGL: WebGL 0.96
GLSL: WebGL GLSL ES 0.96
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"09b19d7a","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"graphing-lines":{"sha":"09afed9e","branch":"HEAD"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"20ce6f04","branch":"HEAD"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"8d290320","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"e5d21051","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@jonathanolson this is successfully fixed in http://www.colorado.edu/physics/phet/dev/olsonjb/maintenance3/graphing-lines_en.html

**Comment by pixelzoom** [comment]
Reopening.

I'd like to know how this was patched - it doesn't resemble any PhET process that I'm familiar with. Eg what's going on with the non-standard "maintenance2" location in the URL above?

I'm also a little concerned about how dramatic a change was required in StringUtils.format, see https://github.com/phetsims/phetcommon/commit/0cac0425531f1af7d45b30975a9b8a87a5d5be91. StringUtils.format is used by most sims, and graphing-lines (afaik) wasn't doing anything unusual. It this indeed a patch (as indicated in the commit message), or is it now in master?

**Comment by pixelzoom** [comment]
Discussed on Skype with @jonathanolson.  The problematic case is when there's no space between direction directives.  This can occur in StringUtils.format with a pattern like '{0}{1}', or in a strings that are loaded with the string plugin and explicitly concatenated with + operator.  Since the problem is not specific to MessageFormat patterns, we should consider handling this in scenery, rather than in StringUtils.format.
