### ISSUE TITLE
Support reproducible random number sequences

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-lines#62]
For https://github.com/phetsims/phet-io/issues/548 we would like to have reproducible random number sequences.  For this sim, it means using phet.joist.random instead of Math.random and _.shuffle.

**Comment by samreid** [comment]
Fixed above, @pixelzoom can you please confirm the changes are complete and correct?

**Comment by samreid** [comment]
You can test it the same way as described in https://github.com/phetsims/function-builder/issues/99

**Comment by samreid** [comment]
Grunt is passing, sim is launching.

**Comment by pixelzoom** [comment]
I inspected the commit, ran the sim, and didn't see any problem.  Closing.
