### ISSUE TITLE
"Challenge 1 of 0"

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-lines#64]
While testing https://github.com/phetsims/scenery-phet/issues/75, I observed
![image](https://cloud.githubusercontent.com/assets/679486/20459987/3fe1719e-ae92-11e6-8e51-1f1adf161541.png)

which says "challenge 1 of 0"

**Comment by pixelzoom** [comment]
@samreid master? published?

**Comment by pixelzoom** [comment]
Never mind... master.

**Comment by pixelzoom** [comment]
Fixed in above commit. This issue was introduced in phetsims/axom#71 on 9/29/16, conversion from PropertySet to Property.  Never made it into a published version.   @samreid Thanks for reporting.  

Closing.
