### ISSUE TITLE
disable showAnswers in production versions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#67]
phetsims/joist#406 is a prerequisite to this.

In GLQueryParameters, set `showAnswers` to false if we're running a production version, so that answers can't be revealed.

**Comment by pixelzoom** [comment]
Deferred until we have a way to identify production versions, see phetsims/joist#406.

**Comment by pixelzoom** [comment]
Done in master, awaiting deployment.

**Comment by KatieWoe** [comment]
Confirmed 1.3.0-rc.1
