### ISSUE TITLE
replace Unicode check marker and X with font-awesome icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#68]
https://github.com/phetsims/unit-rates/issues/180

**Comment by pixelzoom** [comment]
@amanda-phet probably a good idea to address this soon, so that it's rolled into graphing-slope-intercept, yes?

**Comment by amanda-phet** [comment]
Agreed. Let me know if you need anything from me.

**Comment by pixelzoom** [comment]
Done, screenshot shown below. @amanda-phet do you want a dev version to review this, or is the screenshot sufficient?

![screenshot_308](https://cloud.githubusercontent.com/assets/3046552/23820913/1bf55ce0-05e1-11e7-9ba8-28e865110460.png)

**Comment by amanda-phet** [comment]
Screenshot looks good to me. Thanks!
