### ISSUE TITLE
RandomChooser is flawed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#72]
See https://github.com/phetsims/graphing-slope-intercept/issues/8.   Requires major changes to the game in Graphing Lines.

**Comment by pixelzoom** [comment]
Revision in above commit apply primarily to supporting graphing-slope-intercept, and the base types used by both sims.   A similar revision still needs to be done for graphing-lines ChallengeFactory type hierarchy.

**Comment by pixelzoom** [comment]
Revision to graphing-lines have been completed.  RandomChooser has been replaced with ValuePool.  Commits are attached to related issue https://github.com/phetsims/graphing-slope-intercept/issues/8. Lightly tested, full regression test and comparison to design spec still needs to be done.

**Comment by pixelzoom** [comment]
I added query parameter `verifyChallenges`, which creates 2000 sets of challenges for each level.  This exercises the challenge factories more than a typical user could ever do, and is intended to find problems that may only occur with random selection, etc.  It does not verify that the challenges match the design specification.

**Comment by pixelzoom** [comment]
@amanda-phet I'm confident that the challenge factories match the specification, and that there's nothing in the randomness that will cause the sim to fail.  Would you like to review?

**Comment by pixelzoom** [comment]
@amanda-phet FYI, Graphing Lines is on deck for dev testing, this is the only blocking issue.

**Comment by amanda-phet** [comment]
>I'm confident that the challenge factories match the specification, and that there's nothing in the randomness that will cause the sim to fail. Would you like to review? 

I trust you and don't feel a need to review personally.
