### ISSUE TITLE
"Graphing Point-Slope" sim?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#73]
In https://github.com/phetsims/graphing-lines/issues/66, we decided to create a slope-intercept only version of this sim, which was ultimately named "Graphing Slope-Intercept".   As a result of that work, it would be very easy to create a point-slope version, "Graphing Point-Slope".  All we'd need to do is specify a set of challenge factories, similar to what we did in https://github.com/phetsims/graphing-slope-intercept/issues/2.

If such a sim is desirable, there are significant cost advantages to doing it at the same time as "Graphing Slope-Intercept" (and the republication of Graphing Lines that fix https://github.com/phetsims/graphing-lines/issues/72 requires).  The main cost advantages are:
(1) The process for specifying the challenges will be fresh in the minds of @amanda-phet and me.
(2) The process for implementing the challenge factories will be fresh in my mind.
(3) The entire suite of sims can be tested at the same time, allowing us to "spot test" screens that are duplicated between sims.

@amanda-phet Is there any interest having a "Graphing Point-Slope" sim?

**Comment by amanda-phet** [comment]
Hm, my first instinct is no. The slope-intercept form of a line is so prevalent in just about every pre-algebra and algebra curriculum that it demanded its own sim. This is why teachers have asked for slope-intercept to be separate, because it is taught much earlier than point-slope, so the game was hard for those teachers to use. Once a student is learning about point-slope form they are also familiar with slope-intercept, so the game is actually really nice that it has the two forms mixed up. 

However, if others disagree with me I'm happy to listen! I do see your points, @pixelzoom , but as far as the math content goes I don't see a lot of value in isolating point-slope the same way we did with slope-intercept.

**Comment by pixelzoom** [comment]
I figured that was the case in terms of the order in which the topics are taught.  Just wasn't sure if anyone wanted to crank out an easy sim :)

Who are the "others" that should be consulted to resolve this issue?

**Comment by amanda-phet** [comment]
I'm curious what @ariel-phet and @kathy-phet think. I will also email Karina since she worked on Graphing Lines.

**Comment by pixelzoom** [comment]
It would be good to resolve this before diving into graphing-slope-intercept testing because (as mentioned in https://github.com/phetsims/graphing-lines/issues/73#issue-218977118) one of the big cost advantages would be simultaneous testing.

**Comment by amanda-phet** [comment]
My opinion is that we should not make the suggested sim. While it would be inexpensive, (and those sims are rare!), I'm not sure it would be useful, so it could still end up being an unnecessary cost.

**Comment by ariel-phet** [comment]
@amanda-phet on this topic I defer to your judgement. Although I also like inexpensive sims, I do not like "diluting" the impact of a sim (for instance CCK having so many flavors in Java). So if you think it would be low use, especially given the full Graphing Lines that covers all the bases, I am fine with not having a specific point-slope sim.

**Comment by pixelzoom** [comment]
I definitely agreed about the @ariel-phet's "diluting" comment.

**Comment by kathy-phet** [comment]
@amanda-phet - I also defer to you on this topic. We had talked about the advantage of a pure "Slope" sim ... but that was a bit more than a tweak, adding a new (relatively simple) screen so probably not something to hold up the publication of these two sims.

**Comment by amanda-phet** [comment]
Thank you for commenting. Let's skip this spinoff sim, then.
