### ISSUE TITLE
Game timer keeps running after the last challenge is answered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#74]
Game timer keeps running after the last challenge is answered, and doesn't stop until you press Next button. It should stop immediately after answering the last challenge.

**Comment by pixelzoom** [comment]
Fixed.  The game timer now stops as soon as the user has made their final guess on the last challenge.  If their final guess was correct, they'll see a "Next" button that takes them to the "level completed" screen.  If their final guess was incorrect, they'll see a "Show Answer" button before seeing the "Next" button.  They are not charged for time incurred in reviewing an incorrect answer to the final challenge.

**Comment by pixelzoom** [comment]
I'm going to mention this issue in dev testing for graphing-slope-intercept (https://github.com/phetsims/tasks/issues/812), since that's how it was uncovered.

@phet-steele Could you please review this in master?

**Comment by phet-steele** [comment]
Fixed.
