### ISSUE TITLE
pick up the fix for web audio for 1.2 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#76]
Related to dev test https://github.com/phetsims/tasks/issues/816.
Same problem as https://github.com/phetsims/graphing-slope-intercept/issues/17.

Since this sim is in dev testing, there has been no release branch created yet.  But I was hoping to use the same shas that are being testing for graphing-slope-intercept.  We'll see if that's still possible.

**Comment by pixelzoom** [comment]
Looks like we'll need to update to scenery-master to pick up the fix for phetsims/graphing-lines#75.  That's also true for graphing-slope-intercept.  So I think we'll probably just start over with master of everything.

**Comment by pixelzoom** [comment]
Next test version of Graphing Lines will use the same shas as the next test version of Graphing Slope-Intercept, which will come from master in order to pick up the web audio fix. See https://github.com/phetsims/graphing-slope-intercept/issues/17#issuecomment-295396646.

**Comment by pixelzoom** [comment]
The plan is to use master for the next dev (or RC?) version, to pick up this and other fixes.  So closing.

**Comment by phet-steele** [comment]
1.2.0-dev.2 has audio in Safari, and shows pingver=3 and the brand in the network tab, and works with `?phet-android-app`. I'd say we got all three patches! (verified for the dev test)
