### ISSUE TITLE
Long strings that replace variables (y, x, and m) cause equation box to appear under graph

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/graphing-lines#80]
Test device: Macbook Air

Operating System: OSX 10.12.4

Browser: Chrome:  Version 58.0.3029.81 (64-bit)

Problem description:
When I use the query parameter: ?stringTest=long, the text for the equation box and equation  on the graph do not shrink to accommodate the long string.    Is this irrelevant because the text that has been replaced is either y or m or x which are always only one letter anyway?  

Steps to reproduce:
1. Add query parameter: ?stringTest=long to URL
2. When sim opens, choose any of the scenes. 
3. Observe that equation box font size has not shrunk and the is under the graph.

Screenshots:
![12345678901234567890123456789012345678901234567890 screenshot 3](https://cloud.githubusercontent.com/assets/17385784/26286334/ba21beb8-3e30-11e7-95f2-9f904fe68b5d.png)

Related to: phetsims/tasks/issues/843 
Troubleshooting information (do not edit):
Name: ‪Graphing Lines‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.2.0-rc.1/graphing-lines_en.html
Version: 1.2.0-rc.1 2017-05-16 18:40:19 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Language: en-US
Window: 1164x544
Pixel Ratio: 1.100000023841858/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"f475e68c","branch":"HEAD"},"babel":{"sha":"4392e442","branch":"master"},"brand":{"sha":"f4b72cac","branch":"HEAD"},"chipper":{"sha":"3061f107","branch":"HEAD"},"dot":{"sha":"57936fff","branch":"HEAD"},"graphing-lines":{"sha":"dfc4ea9e","branch":"HEAD"},"joist":{"sha":"06775098","branch":"HEAD"},"kite":{"sha":"0cc5b620","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"d0ffe176","branch":"HEAD"},"query-string-machine":{"sha":"e7055778","branch":"HEAD"},"scenery":{"sha":"d1d2ca2d","branch":"HEAD"},"scenery-phet":{"sha":"6dc1a064","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"3967c777","branch":"HEAD"},"tandem":{"sha":"30603e66","branch":"HEAD"},"vegas":{"sha":"6bd734e2","branch":"HEAD"},"vibe":{"sha":"5e8151e1","branch":"HEAD"}}

**Comment by EthanWJohnson** [comment]
Happens on stringTest=rtl too, on the third screen. Not sure how big an issue it is, though; it seems like the letters being replaced would never get that long.

**Comment by pixelzoom** [comment]
This issue was previously reported in https://github.com/phetsims/graphing-lines/issues/57, and we decided not to address it, since it will never occur in practice.  But I will look at addressing it, so that it doesn't keep coming up in the future.

**Comment by pixelzoom** [comment]
I looked into this, and it's more effort than is warranted for something that will never occur in practice.  So closing this issue as "won't fix".
