### ISSUE TITLE
unary minus is a bit long?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#85]
Noted while working on https://github.com/phetsims/graphing-lines/issues/84.

In the Slope screen, the "Slope is..." label on the graph is using a minus operator, rather than the shorter unary minus, for negative slope values.  Example:

![screenshot_509](https://user-images.githubusercontent.com/3046552/37125460-f8548476-2229-11e8-901c-5bbc34ca096e.jpg)

@ariel-phet @amanda-phet in light of our recent discussion about standardizing math symbols (and minus vs unary minus in particular) should this be changed?

**Comment by ariel-phet** [comment]
@pixelzoom this seems like a very quick change....would it be possible to look at a dev version, or version on master with the everything changed to the shorter one? might be easiest to see in context, and compare the published version to the suggested change. 

If it is indeed a quick change of a few lines of code, let me know, and I will take a look on master or such.

**Comment by pixelzoom** [comment]
Yes, quick change, and could provide a dev version. But it doesn't use MathSymbols.js.  So I'd need to know how long you'd like the unary minus to be -- specified as percentage of the currently value shown in screenshots.

**Comment by ariel-phet** [comment]
This would be a decision for @amanda-phet 

@amanda-phet thoughts on making this a bit shorter? I will leave it up to your discretion.

**Comment by pixelzoom** [comment]
@amanda-phet Also fine to leave it as is, since we did decide on this specific length for the unary minus during design of this sim.  I was just noting that it's a tad longer than in other sims.   And to reiterate -- if you'd like me to change it, please specify as a percentage of the current length.

**Comment by amanda-phet** [comment]
I think we can leave it as is for this sim. Since this sim needs to display the minus sign over a grid and sometimes within a sentence ("Slope is...") I think we need it to be extra noticeable.
