### ISSUE TITLE
prioritize active line when color-coding point tool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#89]
When the "active" line intersects a saved line, the point tool's color should be keyed to the active line, not the saved line.   Here's what currently happens:

![screenshot_696](https://user-images.githubusercontent.com/3046552/42656354-44f52ab8-85dc-11e8-9c8b-136d79a2d4d1.png)

The background behind the point coordinates should be black, not gray.

**Comment by pixelzoom** [comment]
Done in master.  Labeled as fixed-awaiting-deploy, so we test in next RC cycle.

**Comment by KatieWoe** [comment]
Confirmed in both Graphing Lines and Graphing Slope-Intercept

**Comment by pixelzoom** [comment]
Fixed in the above commit. @KatieWoe please verify in master. If it looks OK, please leave this issue open to regression test in the next RC.

**Comment by KatieWoe** [comment]
#112 looks good on master
