### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#90]
For phetsims/tasks/issues/953
"Hide lines" and "Hide grid" in title case would be "Hide Lines" and "Hide Grid."
![title case3](https://user-images.githubusercontent.com/41024075/45239006-f59cb700-b2a0-11e8-9c04-5d376907cda7.PNG)

**Comment by pixelzoom** [comment]
There's nothing inconsistent here.  And there is no need to be pedantic about using title case everywhere;  the context needs to be examined when deciding what case to use.

@amanda-phet please advise.

**Comment by pixelzoom** [comment]
The checkboxes in question are being changed to use icons instead of text (see https://github.com/phetsims/graphing-lines/issues/91), so this issue is now irrelevant.  Closing.
