### ISSUE TITLE
use icons for "Hide lines" and "Hide grid"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-lines#91]
In other sims with gridlines (see Area Builder or Area Model sims) we are using this checkbox to toggle gridline visibility:  
![image](https://user-images.githubusercontent.com/7852916/45846379-d82a0d00-bce4-11e8-8d9a-308660a77518.png)

Discussed 9/20/18 that we should include the same checkbox in Graphing Lines and Graphing Slope-Intercept. This means the checkbox would be *checked* on startup. 

This change should happen concurrently with one that replaces the "hide lines" checkbox with a visibility toggle button (see Graphing Quadratics):
![image](https://user-images.githubusercontent.com/7852916/45846517-30f9a580-bce5-11e8-9ec4-a8e579a13692.png)
 
![image](https://user-images.githubusercontent.com/7852916/45846531-38b94a00-bce5-11e8-9308-63e7d43133f7.png)

**Comment by pixelzoom** [comment]
Do you want both of these new checkboxes just outside the lower-right corner of the the graph, ala Graphing Quadratics?  Vertically stacked?  Which one on top?

**Comment by pixelzoom** [comment]
If we do put these 2 controls together, it's going to be odd having a checkbox and a toggle button for similar functions, and it's going to be less clear what the eyeball is referring to.

**Comment by pixelzoom** [comment]
@amanda-phet  I'd like to take care of it while I'm finishing up Graphing Quadratics. Please advise.

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.3.0-dev.3](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.3/phet/graphing-lines_en_phet.html). 

I did what I thought was best for this.  I replaced "Hide lines" with the eyeball checkbox at lower-right of the graph.  And I replaced "Hide grid" with an icon, leaving the checkbox in the panel. See Before/After screenshots below.  Note that the same changes apply to the _Graphing Slope-Intercept_ sim.

Before:

![screenshot_817](https://user-images.githubusercontent.com/3046552/47622342-a9fcd180-dac9-11e8-9fc5-3c9fb4f64c84.png)

After:

![screenshot_816](https://user-images.githubusercontent.com/3046552/47622305-483c6780-dac9-11e8-987f-e4382929e2dd.png)

**Comment by amanda-phet** [comment]
Looks great! This is exactly what I had in mind. 

The only iffy thing is the yellow toggle button doesn't pop on the yellow background like it does in GQ. Should we consider another color? Or is it fine?

**Comment by pixelzoom** [comment]
Yellow does 'pop' a bit - albeit not as much as on a more muted background color.  See screenshot below.

Red would definitely pop more, and fits a bit with the accordion box button. Red is a tad obnoxious, but maybe we want obnoxious for this feature. And if we changed to red here, why not change to red in Graphing Quadratics? See screenshot below. 

We could consider changing the background color, but maybe we don't want to go there. 

![screenshot_819](https://user-images.githubusercontent.com/3046552/47806147-a7cf8880-dcfe-11e8-9481-df2adc84fdd7.png)

![screenshot_820](https://user-images.githubusercontent.com/3046552/47806355-262c2a80-dcff-11e8-81d7-9b173a7a7449.png)

**Comment by pixelzoom** [comment]
@amanda-phet raising priority to high.  If changing the button color to 'red' is desirable, that needs to be done before creating the 1.0 release branch for Graphing Quadratics.

**Comment by amanda-phet** [comment]
Let's leave it yellow.

**Comment by KatieWoe** [comment]
Graphing Lines and Graphing Slope Intercept look ok.
