### ISSUE TITLE
do not disable UI components when graph contents are hidden

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#92]
Currently, checking the "Hide lines" checkbox results in some of the other UI components being disabled (other checkboxes, Save and Erase buttons, ...)

In Graphing Quadratics, we decided _not_ to disable other UI components. From https://github.com/phetsims/graphing-quadratics/issues/34:
> When contents of graph are hidden (using eyeball toggle), do not disable other controls (checkboxes, save/erase button)

Do we want to do the same in Graphing Lines?

**Comment by pixelzoom** [comment]
@amanda-phet If this is something you'd like to do, then I'd like to take care of it while I'm finishing up Graphing Quadratics. Please advise.

**Comment by pixelzoom** [comment]
As the result of work done for #91, the old code that handled enabling/disabling UI components was no longer applicable and was removed in the above commit.  If we want to continue to disable components when the graph contents are hidden, I'll need to re-implement that.  

@amanda-phet please review [1.3.0-dev.4](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.4/phet/graphing-lines_en_phet.html).  It behaves like Graphing Quadratic; that is, nothing is disabled when the graph contents are hidden.   If that is what you'd like, then you can close this issue.  Otherwise assign back to me if you'd like the old behavior re-implemented.

**Comment by amanda-phet** [comment]
I don't mind the new behavior, but I think it would be good for @ariel-phet and @kathy-phet to review as well.

**Comment by ariel-phet** [comment]
Looks good, I think we can close @pixelzoom

**Comment by pixelzoom** [comment]
Great, thanks @ariel-phet. I'm not going to close - I've labeled as "fixed-awaiting-deploy" and will close after we've deployed this change.

**Comment by KatieWoe** [comment]
Looks good on Graphing Lines and Graphing Slope Intercept
