### ISSUE TITLE
use icons for save and erase buttons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#93]
Do we want to change Graphing Lines to use icons for the save/erase buttons?

Graphing Lines:

![screenshot_761](https://user-images.githubusercontent.com/3046552/45965281-50464a80-bfe5-11e8-96e7-258947a62985.png)

Graphing Quadratics:

![screenshot_760](https://user-images.githubusercontent.com/3046552/45965252-3d337a80-bfe5-11e8-9fb8-5980993e71c2.png)

**Comment by amanda-phet** [comment]
No. We discussed this and decided since you can save many lines in GL but only one in GQ, it makes sense that they have different appearances.
