### ISSUE TITLE
use standard font for math symbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#94]
Graphing Lines does not use the font that PhET has standardized on for math symbols (italic Times New Roman). Should we update it to do so?   For example, _x_, _y_, _m_, _a_, _b_, _c_ in:

Graphing Lines:

![screenshot_762](https://user-images.githubusercontent.com/3046552/45965472-ca76cf00-bfe5-11e8-9b28-ebf7a71a3367.png)

Graphing Quadratics:

![screenshot_763](https://user-images.githubusercontent.com/3046552/45965479-cfd41980-bfe5-11e8-96fa-b041699257db.png)

**Comment by amanda-phet** [comment]
Yes, we should definitely update the font to be in sync with the newest math sims.

**Comment by pixelzoom** [comment]
Notes on how to do this...

See GQSymbols for a good approach to creating symbols that contain the appropriate markup for RichText.

Verify that MathSymbols is used throughout for equals, plus, minus, etc.

Symbols appear in:
* checkbox labels
* equation titles on AccordionBoxes
* interactive equations
* equations on lines
* Game challenges

**Comment by pixelzoom** [comment]
This needs to be addressed (at least partially) for Graphing Quadratics, see https://github.com/phetsims/graphing-quadratics/issues/93.

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.3.0-dev.2](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.2/phet/graphing-lines_en_phet.html).   

While Graphing Quadratics uses 'normal' font weight for equations, Graphing Lines uses 'bold'.  I don't know if that's something we need to change, but it's trivial to do so.  Let me know if you'd like to see a dev version of Graphing Lines with 'normal' weight.

**Comment by amanda-phet** [comment]
Looks great to me! Let's keep bold. 

I didn't look through all game challenges, but a quick review of everything looked really nice to me.

**Comment by pixelzoom** [comment]
Thanks. Marking as "fixed awaiting deploy".

**Comment by lmulhall-phet** [comment]
@amanda-phet @pixelzoom are we OK with the math text being bold?

GSI 1.1.0-rc.1
![screen shot 2019-02-04 at 11 37 09 am](https://user-images.githubusercontent.com/31285590/52229137-64daff00-2871-11e9-9ce5-9ffffa21c153.png)
![screen shot 2019-02-04 at 11 37 16 am](https://user-images.githubusercontent.com/31285590/52229144-67d5ef80-2871-11e9-839d-1babaf12b304.png)

GQ screenshot used by @pixelzoom in https://github.com/phetsims/graphing-lines/issues/94#issue-363226080
![gq](https://user-images.githubusercontent.com/31285590/52229203-9a7fe800-2871-11e9-88de-1eb71e045b50.png)

**Comment by pixelzoom** [comment]
This issue deals with the font (not the font weight, e.g. 'bold') used for math symbols.  Font and weight are specified separately. The font weight remains the same as it was in the published version of Graphing Lines and Graphing Slope-Intercept.

That said... Graphing Lines and Graphing Slope-Intercept use `weight: 'bold'` a lot, while Graphing Quadratics uses bold much more judiciously (and to my eye, has a cleaner look).   If that's something we want to change, it would be a new issue. And I don't feel like it's something that should be changed this late in the game for this RC, but that's @amanda-phet's call.

**Comment by amanda-phet** [comment]
When we made the decision to use the math font in this sim, we all agreed the appearance looked good (even if we didn't explicitly discuss the weight). I am happy keeping it bold, and I think it works well in this sim next to all of those pickers.

**Comment by pixelzoom** [comment]
Back to you @lmulhall-phet.

**Comment by lmulhall-phet** [comment]
We'll close this issue after testing on a few more platforms.

**Comment by pixelzoom** [comment]
@lmulhall-phet @KatieWoe Since phetsims/QA#277 and phetsims/QA#278 have been completed, can this issue be closed?

**Comment by KatieWoe** [comment]
Yes
