### ISSUE TITLE
equations are not simplified in Point-Slope screen 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#97]
In master and the published version ([1.2.4](https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html)), equations on the graphed line are simplified in the _Slope Intercept_ screen, but not in the _Point-Slope_ screen.  See screenshots below.  I don't recall if this was intentional and it seems odd.

@amanda-phet please advise.

![screenshot_815](https://user-images.githubusercontent.com/3046552/47621806-c34e4f80-dac2-11e8-952a-905f55376986.png)

![screenshot_814](https://user-images.githubusercontent.com/3046552/47621780-4f13ac00-dac2-11e8-8809-04ed30233334.png)

**Comment by pixelzoom** [comment]
I consulted the [Graphing Lines HTML5](https://docs.google.com/document/d/1UvtIOLKMcJvOw8weN5vcuSRH64QaowLlCBx6Hfz45cs/edit) design document, but it has very little information on the _Point-Slope_ screen, and doesn't address this topic at all.

**Comment by amanda-phet** [comment]
I would guess it was intentional (remember when I originally wanted vertex form to look less simplified?). @ariel-phet probably knows. 

I just checked the original (java) design doc, and this is stated in the 9/13/12 meeting notes: 
>For point-slope if “0” is in the equation for instance (y-0)= ¾(x-0) we will write the equation as y=3/4x.


@ariel-phet let us know if you recall an explicit decision to keep point-slope unsimplified.

**Comment by pixelzoom** [comment]
> I would guess it was intentional (remember when I originally wanted vertex form to look less simplified?).

Yep :)

I just think it's odd that slope-intercept form is simplified, and point-slope form is not.  So I suspect that this might be an oversight.

**Comment by amanda-phet** [comment]
I agree, and seeing the old meeting notes decision makes me think we should simplify that equation.

**Comment by ariel-phet** [comment]
@amanda-phet @pixelzoom it may well have been intentional (at the time the thinking was perhaps that point slope is a bit more difficult to reconcile). However, this was too long ago for me to recall, and I am certainly fine with it being simplified. In fact, I believe one of our rationales for simplifying is it gives a bit of an "implicit challenge" for "why is the line labeled this way when the equation is this seemingly different beast" -- so from that point of view, it seems useful to simplify.

**Comment by pixelzoom** [comment]
OK, I'll proceed with simplifying the point-slope form.

**Comment by pixelzoom** [comment]
Note to self: This is isolated to `PointSlopeEquationNode`, but will involve rewriting most of it. Not a quick change, but not rocket science.

**Comment by pixelzoom** [comment]
@amanda-phet please review in [1.3.0-dev.5](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.5/phet/graphing-lines_en_phet.html).

As I got into this, it was not totally clear what "simplified" was for point-slope form.   It seems to me that simplified form for point-slope would be the same as simplified form for slope-intercept. So what I did was to just remove cases where '0' showed up in the equation that's used to label the line.   So you'll still see equations like `(y - 1) = 2x`.  And that's probably what we want, but I wanted to confirm.

**Comment by amanda-phet** [comment]
True, I should have been explicit about simplified form. This also means that the left-hand side of the equation should not have parentheses (ever). Is that tricky to fix at this point?

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.3.0-dev.6](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.6/phet/graphing-lines_en_phet.html).

There's one case that looks a little odd, the case where slope is 1.  See screenshot below - no parens on the left, but parens on the right.  This is the only case like this, so maybe it's OK.

![screenshot_832](https://user-images.githubusercontent.com/3046552/48032707-eeb1e980-e115-11e8-9f75-8e5d61e8930c.png)

**Comment by amanda-phet** [comment]
Hm... is it difficult to get rid of those parentheses in the case of m=1? (but not m=-1). Otherwise it all looks good to me.

**Comment by pixelzoom** [comment]
In [1.3.0-dev.8](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-dev.8/phet/graphing-lines_en_phet.html), the parens around `x - x1` have been removed when m=1.  @amanda-phet please verify.

I also wanted to point out that these point-slope "simplifications" apply to _all non-interactive equations_ - not just the equations that are used to label lines on the graph, but also to any non-interactive equations that appear in the game.  So you might want to take a very close look at the _Line Game_ screen. Below are some examples, running master with `?showAnswers`.

![screenshot_837](https://user-images.githubusercontent.com/3046552/48110716-e8516980-e20a-11e8-9a6e-21f89befbd76.png)

![screenshot_836](https://user-images.githubusercontent.com/3046552/48110695-c8ba4100-e20a-11e8-8a69-e183f5798b5a.png)

![screenshot_834](https://user-images.githubusercontent.com/3046552/48110556-108c9880-e20a-11e8-9c71-d616e99e0b5c.png)

![screenshot_835](https://user-images.githubusercontent.com/3046552/48110646-7e38c480-e20a-11e8-8955-ba535755b1d4.png)

**Comment by KatieWoe** [comment]
Looks good to me 1.3.0-rc.1
