### ISSUE TITLE
revise screenshots for 1.3.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-lines#99]
The changes in #91 and #94 have changed how this sim looks, so screenshots will need to be revised, including:

- [x] graphing-lines-screenshot.png
- [x] graphing-lines-screenshot-alt1.png
- [x] graphing-lines-screenshot-alt2.png
- [x] graphing-lines-screenshot-alt3.png

This needs to be done before 1.3.0 publication.

**Comment by amanda-phet** [comment]
@KatieWoe Can you re-create the GL screenshots using the latest dev version? There were some visual changes to the sim, but the sim configurations do not need to change. Feel free to paste them here for me to verify if you would like.

**Comment by KatieWoe** [comment]
@amanda-phet 
![graphing-lines-screenshot](https://user-images.githubusercontent.com/41024075/48221218-bb0dd400-e34e-11e8-878b-f964f97a9def.png)
![graphing-lines-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48221219-bb0dd400-e34e-11e8-8f4e-8246b202271b.png)
![graphing-lines-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48221220-bba66a80-e34e-11e8-93a3-bf511580d88d.png)
![graphing-lines-screenshot-alt3](https://user-images.githubusercontent.com/41024075/48221221-bba66a80-e34e-11e8-87f6-ddf42ff574de.png)

**Comment by amanda-phet** [comment]
The slope screen is just missing the saved line at y=-2. 

For point-slope, let's do a different equation that makes it easier to see the equation on the line. How about y-3 = -8/12 (x - -5) 
![image](https://user-images.githubusercontent.com/7852916/48221705-04125800-e350-11e8-9014-76880f523638.png)


Thanks!

**Comment by KatieWoe** [comment]
@amanda-phet 
![graphing-lines-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48233407-4351a080-e372-11e8-8176-12d1bdb835e5.png)
![graphing-lines-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48233408-4351a080-e372-11e8-918d-d8afe5ef13ec.png)

**Comment by amanda-phet** [comment]
Point-slope looks good.

Can you just make sure the Slope screen has y=-2, not y=2? The horizontal line should go through that purple point.

**Comment by KatieWoe** [comment]
@amanda-phet 
![graphing-lines-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48362370-be5fd300-e660-11e8-9457-4ce8266cb7d2.png)

**Comment by amanda-phet** [comment]
You got it- thanks!

**Comment by KatieWoe** [comment]
Above commit should do it.  @amanda-phet @pixelzoom look over and close if acceptable.

**Comment by pixelzoom** [comment]
I verified that the screenshots in GitHub match what @amanda-phet approved in the above comments, and that images sizes are the new standard 1536x1008.

Closing.
